import { FIELD_SCENARIOS, matches, fieldActionRisk } from './field.js?v=20261001-contact';
import { installKeyboardNavigation } from './keyboard.js';
import { MODULES, CREW, TOOLS, ENVIRONMENTS, ANOMALIES, RELICS, DISEASES, COMMANDS, MODES, SCENES } from './data.js';
import { newRun, reduce, active, capable, anomaly, mystery, scenarioDesign, outcomeAvailable, correctPredictionCount, commandPreview, intent, returnRisk, ascentOptions, eventOptions, resonance, visibleClues, equipped, powerCap, effectivePower } from './engine.js?v=20261001-contact';
import { KEYS, readRun, readMeta, updateMeta } from './save.js?v=20261001-contact';
const $=sel=>document.querySelector(sel), app=$('#app'), dialog=$('#dialog');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null, screen='title', draft={seed:'',tool:'silent'}, pending=null, saveError='', saved=null, meta, settings={sound:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const FOCUS_SCENARIO='A07';
let storage;try{storage=localStorage;meta=readMeta(storage);saved=readRun(storage);const v=JSON.parse(storage.getItem(KEYS.settings));if(v)settings={sound:!!v.sound,reduced:!!v.reduced};}catch(e){meta=meta||{version:1,bestDepth:0,bestScore:0,returns:0,discoveries:{},endings:[],runs:[],tutorial:[]};saveError=e.message;}
if(saved){if(saved.node?.anomaly===FOCUS_SCENARIO)saved.focusScenario=FOCUS_SCENARIO;else if(saved.focusScenario!==FOCUS_SCENARIO)saved=null;}
if(saved?.focusScenario&&!saved.field&&saved.phase!=='route'&&saved.phase!=='result'){saved=null;saveError='旧方式の途中データは新しい調査方式では再開できません。調査記録は保持しています。新しい調査を開始してください。';}
let audio, narrationTimer=null, lastNarrationKey='';
function tone(kind='click'){if(!settings.sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='damage'?'sawtooth':'sine';o.frequency.setValueAtTime({click:520,sonar:840,damage:90,success:660,result:340}[kind]||240,audio.currentTime);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.3);}catch{}}
function persist(){try{if(state){storage.setItem(KEYS.run,JSON.stringify(state));saved=state;}storage.setItem(KEYS.meta,JSON.stringify(meta));storage.setItem(KEYS.settings,JSON.stringify(settings));}catch{saveError='保存できません。ブラウザの保存領域を確認してください。現在のランはこの画面で続けられます。';}}
const btn=(label,action,attrs='',cls='')=>`<button type="button" data-action="${action}" class="${cls}" ${attrs}>${label}</button>`;
const small=(text)=>`<span class="eyebrow">${text}</span>`;
const crewOptions=(all=false)=>state.crew.filter(c=>all||active(c)).map(c=>`<option value="${c.id}">${c.name} · 体力${c.hp} / 疲労${c.fatigue}</option>`).join('');
function select(name,options,label){return `<label>${label}<select name="${name}">${options}</select></label>`;}
function meter(name,value,max,cls=''){return `<div class="meter ${cls}"><div><span>${name}</span><strong>${value}<small> / ${max}</small></strong></div><progress value="${value}" max="${max}"></progress></div>`;}
function sonar(){return `<div class="sonar" aria-hidden="true"><i></i><i></i><i></i><div class="sweep"></div><span class="echo e1"></span><span class="echo e2"></span><span class="echo e3"></span><div class="crosshair">+</div></div>`;}
function sceneArt(scene,extra='',narration=null){
 if(!scene)return '';
 const followup=narration?.followup?`<div class="scene-followup"><strong>${escape(narration.followup.title)}</strong><span>${escape(narration.followup.text)}</span></div>`:'';
 const dialogue=narration?`<div class="scene-dialogue scene-update" aria-label="${escape(`${narration.title}。${narration.text}${narration.followup?`。${narration.followup.title}。${narration.followup.text}`:''}`)}"><strong>${escape(narration.title)}</strong><p aria-hidden="true" data-typewriter data-text="${escape(narration.text)}" data-key="${escape(narration.key)}" data-delay="${narration.delay??1200}"></p>${followup}<span class="sr-only">${escape(narration.text)}${narration.followup?`。${escape(narration.followup.title)}。${escape(narration.followup.text)}`:''}</span></div>`:'';
 const overlay=dialogue?`<div class="scene-overlay">${dialogue}</div>`:'';
 return `<figure class="narrative-art ${extra} ${overlay?'has-dialogue':''}"><img src="${scene.src}" alt="${escape(scene.alt)}" decoding="async">${overlay}<figcaption><span>OBSERVATION IMAGE</span><span>白黒深海記録</span></figcaption></figure>`;
}
function sceneForState(){if(!state)return SCENES.anomalies[FOCUS_SCENARIO]||SCENES.splash;if(state.focusScenario&&state.phase==='route')return SCENES.anomalies[state.focusScenario];if(state.phase==='event'&&Number.isInteger(state.node?.event))return SCENES.events[state.node.event]||SCENES.environments[state.depth];if(state.phase==='core')return SCENES.anomalies.F01;const anomalyPhases=['investigation','deduction','verification','crisis','aftermath','hypothesis','preparation','encounter','reward'];if(anomalyPhases.includes(state.phase)){const current=anomaly(state);if(current&&SCENES.anomalies[current.id])return SCENES.anomalies[current.id];}return SCENES.environments[state.depth]||SCENES.splash;}
function scenarioSummary(){
 const current=anomaly(state),env=ENVIRONMENTS[state.depth];
 if(current&&['investigation','deduction','verification','crisis','aftermath','hypothesis','preparation','encounter','reward','core'].includes(state.phase))return {title:current.name,text:current.intro};
 if(state.phase==='route'){if(state.focusScenario){const focus=ANOMALIES.find(a=>a.id===state.focusScenario);return {title:focus.name,text:focus.intro};}return {title:env.place,text:env.text};}
 if(state.phase==='event')return {title:state.node?.event===null?'船内通信':eventNames()[state.node.event],text:'通信回線が開いた。返答を待っているのは、誰だろう。'};
 if(state.phase==='safe')return {title:'安全域',text:'海が、静かになった。ここで一度だけ、船か隊員を整えられる。'};
 if(state.phase==='decision')return {title:'進路判断',text:state.resolution==='retreat'?(current?.story?.retreat||'異常から離脱した。持ち帰った記録と残された資源から、次の航路を決める。'):'さらに深く進むか、ここから帰還するか。船の状態と持ち帰る記録を見比べる。'};
 if(state.phase==='ascent'){const titles=['浮上 I — 遺物の共鳴','浮上 II — 記憶の混線','時間共鳴 — 余分な一秒'];return {title:titles[state.ascentStep],text:state.ascentStep===0?'船内の物体が、船体の外から響いている。何かを切り離さなければならない。':'海面の呼出信号が、昨日の声で聞こえる。自分たちを現在へつなぎとめる。'};}
 return {title:env.place,text:env.text};
}
function sceneNarration(){
 if(!state)return null;
 if(state.field&&state.phase==='investigation'){const r=state.field.last;return r?{key:`field:${r.id}`,title:r.measurement?'観測':'船内変化',text:r.text,delay:550}:null;}
 const current=anomaly(state),env=ENVIRONMENTS[state.depth],key=`${state.node?.id||state.depth}:${state.phase}`;
 if(state.phase==='route')return null;
 if(['event','safe','ascent','decision'].includes(state.phase))return null;
 if(!current)return null;
 if(state.phase==='investigation'){
  const found=state.investigationResult;
  return found?{key:`${key}:${state.sites.length}:${found.site}`,title:'発見',text:found.observation,followup:found.reaction?{title:'船内変化',text:found.reaction}:null,delay:550}:null;
 }
 if(state.phase==='verification'){
  const found=state.experimentResults?.at(-1);
  if(found)return {key:`${key}:${state.experimentResults.length}:${found.id}`,title:found.predictionCorrect===null?'実証結果':found.predictionCorrect?'予測一致':'予測不一致',text:`${found.name}。${found.result}${found.reaction?`　${found.reaction}`:''}`,delay:550};
 }
 if(scenarioDesign(state)&&['deduction','verification','crisis'].includes(state.phase))return null;
 let title='',beat='';
 if(['deduction','hypothesis','preparation','verification'].includes(state.phase)&&current.story?.discovery){title='異常の兆候';beat=current.story.discovery;}
 else if(['crisis','encounter'].includes(state.phase)&&current.story?.encounter){title='遭遇';beat=current.story.encounter;}
 else if(state.phase==='aftermath'&&state.mysteryOutcome){title=state.mysteryOutcome.name;beat=state.mysteryOutcome.text;}
 else if(state.phase==='reward'){title='収束';beat=current.story?.resolved||`法則は「${current.hypotheses[current.correct]}」。異常の反応は収まり、回収できるものだけが残った。`;}
 if(!beat)return null;
 return {key:`${key}:${state.mysteryOutcome?.id||''}:${state.encounter?.turn||''}`,title,text:beat};
}
function startNarration(){clearTimeout(narrationTimer);const text=$('[data-typewriter]');if(!text)return;const box=text.closest('.scene-dialogue'),copy=text.dataset.text||'',key=text.dataset.key||'',delay=Number(text.dataset.delay)||1200;if(settings.reduced||key===lastNarrationKey){box.classList.add('visible','complete');text.textContent=copy;lastNarrationKey=key;return;}lastNarrationKey=key;text.textContent='';let index=0;const type=()=>{index++;text.textContent=copy.slice(0,index);if(index<copy.length)narrationTimer=setTimeout(type,32);else box.classList.add('complete');};narrationTimer=setTimeout(()=>{box.classList.add('visible');type();},delay);}
function title(){return `<main class="title-screen"><section class="title-copy">${small('CONTACT TEST / 接触と帰還の改善試作')}<h1>深淵異常<br>調査船<span>ABYSSAL ARCHIVE</span></h1><p class="lead">三人の呼吸の間に、<br>もう一人いる。</p><p class="muted">現在は「四人目の呼吸」だけを徹底的に検証する重点調査版です。機器を操作し、条件を変えて測り直す。自分の観測から、何を持ち帰るかを決めてください。</p><div class="title-actions">${btn('調査を開始 →','launch','','primary')}${saved&&saved.phase!=='result'?btn('前回の調査を再開','resume'):''}${btn('調査記録','archive')}</div><p class="muted">1人用 / 推理・実証 / 自動保存 / PC向けプロトタイプ</p>${saveError?`<p class="warning">${escape(saveError)}</p>`:''}</section><section class="title-radar">${sceneArt(SCENES.anomalies[FOCUS_SCENARIO],'title-art')}<p class="radar-caption">FOCUS ANOMALY A07<br><strong>FOURTH BREATH</strong><br>乗員数：3 / 検出呼吸：4</p></section></main>`;}
function launch(){return `<main class="launch panel"><section class="launch-visual">${small('CASE BRIEF / 重点調査')}<h1>四つ目の呼吸を追う。</h1><p>機器を操作し、条件を変えて観測する。<br>何が起きるかは、あなたが確かめる。</p>${sceneArt(SCENES.anomalies[FOCUS_SCENARIO])}</section><section class="launch-options"><h2>現場にあるもの</h2><p>集音器・協力者・録音機・隔離区画</p><p>三人で帰り、観測記録を持ち帰るのが最初の目標です。名前を聞くか、標本まで回収するかは、あなたが決めます。接触には酸素を使い、反応圧が増します。4で配管破裂。冷却弁は酸素2で圧を2下げます。浮上用の酸素2は残してください。測定・比較・考える時間は無料です。</p><p class="muted">現在は一件の固定条件で、調査の手触りを検証しています。</p><div class="actions">${btn('重点調査を開始 →','start','','primary')}${btn('タイトルへ','title')}</div></section></main>`;}
function scenarioIntro(){const current=anomaly(state),scene=sceneForState();return `<main class="scenario-intro" aria-label="${escape(current.name)}"><figure><img src="${scene.src}" alt="${escape(scene.alt)}" decoding="async"></figure><section><div class="scenario-copy"><span>ANOMALY CONTACT / 異常接触</span><h1><ruby>${escape(current.name)}<rt>${escape(current.reading||current.name)}</rt></ruby></h1><p>${escape(current.intro)}</p></div>${btn('調査へ進む →','dismissIntro','','scenario-continue primary')}</section></main>`;}
const phases={route:'航路選択',event:'船内通信',investigation:'調査',deduction:'推理',verification:'推理・実証',crisis:'最終決断',aftermath:'結末',hypothesis:'仮説',preparation:'船内準備',encounter:'遭遇',reward:'調査成果',decision:'進路判断',safe:'安全域',core:'記録核',ascent:'浮上',result:'調査結果'};
const objectives={route:'危険と報酬を比べ、航路を1つ選んでください。',event:'この出来事に、どう対処しますか。',investigation:'担当と道具を決め、3地点のうち2地点以上を調査。',deduction:'発生条件・正体・対処法を証拠から組み立てる。',verification:'固有の実験で推理を試し、必要なら修正する。',crisis:'どこまで真相へ踏み込み、何を持ち帰るか決める。',aftermath:'選択が生んだ結末と、判明した真相を記録する。',hypothesis:'手掛かりから法則を推測してください。',preparation:'隊員・遺物・電力を配置して、使う命令を準備。',encounter:'予兆を読み、4つの解法のいずれかを達成。',reward:'法則を確認して、報酬を1つ選んでください。',decision:'帰還に必要な資源を残せていますか。',safe:'安全な水域です。1回だけ修理または休息。',core:'ミナモの記録は、明日のあなたを描いている。',ascent:'海面まで、あと少し。代償を選んでください。'};
function header(){return `<header><a href="#" data-action="title" class="brand">◎ <span>ABYSSAL ARCHIVE<small>海洋異常記録局 / KAIROS 7</small></span></a><nav>${btn(settings.sound?'音 ON':'音 OFF','sound',`aria-pressed="${settings.sound}"`,settings.sound?'toggle-on':'')}${btn(settings.reduced?'動き OFF':'動き ON','motion',`aria-pressed="${!settings.reduced}"`)}${btn('？','help','aria-label="遊び方を開く" aria-haspopup="dialog" title="遊び方"','help-button')}${btn('記録','archive')}${btn('設定','settings')}</nav></header>`;}
function fieldStatus(){if(state.phase==='aftermath')return `<aside class="status panel">${small('RETURN / 海面到達')}${meter('▰ 船体',state.hull,12)}${meter('◉ 残り酸素',state.oxygen,10)}<p>浮上用の酸素2を使用し、帰還しました。</p><p>これ以上の接触は行いません。調査報告で、成果と代償を確認してください。</p></aside>`;return `<aside class="status panel">${meter('▰ 船体',state.hull,12,state.hull<=4?'danger':'')}${fieldSituation()}<h3>乗員 ${state.crew.filter(active).length} / 3</h3><p class="muted">アオイ：${state.field.values.casualty?'応答なし':state.field.values.person==='lock'?'隔離区画':'寝台'}<br>緊急供給：${state.field.values.reserveUsed?'使用済み':'残り1回'}</p><details class="log"><summary>航海ログ</summary>${state.history.slice(-8).reverse().map(h=>`<p>${escape(h.summary)}</p>`).join('')}</details></aside>`;}
function status(){if(state.field)return fieldStatus();return `<aside class="status panel">${small('VESSEL STATUS / 艇内監視')}${meter('▰ 船体',state.hull,12,state.hull<=4?'danger':'')}${meter('◉ 酸素',state.oxygen,10,state.oxygen<=3?'danger':'')}${meter('※ 汚染',state.contamination,8,'violet')}<h3>乗員 <span class="muted">${state.crew.filter(active).length} / 3 活動中</span></h3>${state.crew.map(c=>`<details class="crew ${!active(c)?'inactive':''}"><summary><b>${c.name}</b><span>${active(c)?'● 活動可能':'× 行動不能'}</span><small>体力 ${'●'.repeat(c.hp)}${'○'.repeat(3-c.hp)} / 疲労 ${c.fatigue}/4</small></summary><p>${c.role} · ${c.text}</p><p>${c.fatigue>=3?'固有能力：無効':''}</p>${c.diseases.map(d=>`<p>※ ${DISEASES[d.id].name}${d.stable?'（安定）':''}<br>${DISEASES[d.id].text}</p>`).join('')||'<p>異常なし</p>'}</details>`).join('')}<div class="score-status"><span>調査点</span><strong>${state.score}</strong></div><details><summary>遺物 ${state.relics.length}/4 ・共鳴</summary>${state.relics.map(id=>{const r=RELICS.find(r=>r.id===id);return `<p><b>${r.name}</b><br>＋${r.benefit}<br>△${r.side}</p>`;}).join('')||'<p>未回収</p>'}${['音響','生体','時間'].filter(t=>resonance(state,t)).map(t=>`<p>◎ ${t}共鳴が発動</p>`).join('')}</details><details class="log"><summary>航海ログ <small>最新8件</small></summary>${state.history.slice(-8).reverse().map(h=>`<details><summary>${escape(h.summary)}</summary><small>${h.category} / TURN ${h.turn}</small>${h.details.map(d=>`<p>${escape(d)}</p>`).join('')}</details>`).join('')}</details></aside>`;}
const clueText=(a,i)=>scenarioDesign(state)?.investigations?.[i]?.observation||a.clues[i];
function clues(){if(state.field)return `<div class="clues"><h3>自分の観測記録</h3><p>同じ場所を別の条件で測り、差を確かめてください。結論は自動で記入されません。</p>${btn('記録を比較','fieldJournal')}<p>${state.field.records.filter(r=>r.measurement).length} 件の測定</p></div>`;const a=anomaly(state);if(!a)return '';return `<div class="clues">${small('EVIDENCE / 観測記録')}${visibleClues(state).map((i)=>`<article><span>観測 ${i+1}</span><p>${clueText(a,i)}</p></article>`).join('')||'<p class="muted">まだ手掛かりはない。</p>'}${meta.discoveries[a.id]?`<details class="known"><summary>過去の調査記録</summary><p>${clueText(a,0)}</p></details>`:''}${visibleClues(state).length>=2?`<p class="hint">結論ではなく、条件が違う二つの記録として比べてください。</p>`:''}</div>`;}
function board(edit=true){return `<section class="ship"><div class="section-head"><h2>カイロス7 <small>船内断面</small></h2><span>ϟ ${state.modules.reduce((n,m)=>n+m.power,0)} / ${state.power} 配分</span></div><p class="muted">電力は毎ターン利用する出力です。隊員のいる設備で命令を実行できます。</p><div class="ship-grid">${state.modules.map((m,i)=>`<article class="module ${m.crew?'staffed':''}"><h3><span>${MODULES[i].icon}</span> ${MODULES[i].name}</h3><p class="module-effect">${MODULES[i].effect}</p>${edit?`<label>担当<select data-config="crew" data-module="${i}" aria-label="${MODULES[i].name}の隊員"><option value="">無人</option>${state.crew.map(c=>`<option value="${c.id}" ${c.id===m.crew?'selected':''} ${!active(c)?'disabled':''}>${c.name}${!active(c)?'（行動不能）':''}</option>`).join('')}</select></label>`:`<p>${state.crew.find(c=>c.id===m.crew)?.name||'無人'}</p>`}<div class="power-control">${edit?btn('−','power',`data-module="${i}" data-amount="${m.power-1}" aria-label="${MODULES[i].name}の電力を減らす" ${m.power===0?'disabled':''}`):''}<span>ϟ ${m.power} <small>有効${effectivePower(state,i)}</small></span>${edit?btn('＋','power',`data-module="${i}" data-amount="${m.power+1}" aria-label="${MODULES[i].name}の電力を増やす" ${m.power>=powerCap(state,i)||state.modules.reduce((n,m)=>n+m.power,0)>=state.power?'disabled':''}`):''}</div>${edit?`<label>遺物<select data-config="relic" data-module="${i}" aria-label="${MODULES[i].name}の遺物"><option value="">接続なし</option>${state.relics.map(id=>`<option value="${id}" ${m.relic===id?'selected':''}>${RELICS.find(r=>r.id===id).name}</option>`).join('')}</select></label>`:`<small>${RELICS.find(r=>r.id===m.relic)?.name||'遺物なし'}</small>`}${state.contamination===8?'<p class="warning">※ 全設備異常：有効電力−1</p>':''}</article>`).join('')}</div></section>`;}
function commandCards(clickable=true){return `<div class="commands">${COMMANDS.map(c=>{const p=commandPreview(state,c.id);return `<button type="button" ${clickable?'data-action="command"':''} data-id="${c.id}" ${!p.available||!clickable?'disabled':''} class="command ${p.available?'available':'unavailable'}" title="${escape(p.reason||`${p.mode?MODES[p.mode]+'+'+p.value:''} / ${p.extra||'継続コストなし'}`)}"><strong>${c.name}</strong><span>${p.mode?`${MODES[p.mode]} +${p.value}`:'補助命令'} · ϟ${p.cost}</span><small>${p.reason||p.extra||'追加コストなし'}</small></button>`;}).join('')}</div>`;}
function route(){return `<div class="cards routes">${state.routes.map((n,i)=>{const a=ANOMALIES.find(a=>a.id===n.anomaly);return `<article class="card"><span class="eyebrow">${state.focusScenario?'FOCUS CASE':'ROUTE 0'+(i+1)} / ${n.kind}</span><h3>${state.focusScenario?a.name:['沈んだ航路標','遠方の反応','途切れた救難信号'][i]}</h3><p>危険タグ：${a.tags.join(' / ')}<br>予測：${state.focusScenario?'調査・推理・複数の結末':n.kind==='遺物'?'遺物・調査記録':n.kind==='救難'?'船内イベント・調査記録':'手掛かり・資源'}</p><p class="muted">${state.contamination>=4?'△ ミオの航路予測には未知信号が混入':'△ '+n.risk} / 酸素−1</p>${btn(state.focusScenario?'この事案を調査する →':'この航路を選ぶ →','route',`data-id="${n.id}"`,'primary')}</article>`;}).join('')}</div><p class="muted">${state.focusScenario?'現在は「四人目の呼吸」のゲーム性を検証する重点調査版です。':`通常調査 ${state.completed}/6 → 最終異常 → 浮上2区間`}</p>`;}
function investigation(){if(state.field)return fieldView();const a=anomaly(state),design=scenarioDesign(state),sites=design?.investigations||['外部残骸','反応の中心','接触標本'].map((name,i)=>({name,discipline:['航海','研究','技術'][i],question:['物理痕跡から候補を絞る','現象と行動の関係を探る','直接接触で条件を確かめる'][i],risk:`${i===2?'適性・道具なしで船体−1':'遠隔調査'}`}));return `${state.investigationResult?`<p class="observation-impact"><strong>今回の変化：</strong>${state.investigationResult.impact} / ${state.investigationResult.cost}</p>`:''}<div class="form-row">${select('investigator',crewOptions(),'調査担当')}${select('investTool',`<option value="yes">${TOOLS.find(t=>t.id===state.tool).name}${state.toolUsed?'（消費済み）':''}</option><option value="no">使用しない</option>`,'道具')}</div>${equipped(state).includes('lens')?`<p class="hint">潮目レンズの予見：${clueText(a,[0,1,2].find(i=>!state.sites.includes(i))??0)}</p>`:''}<div class="cards investigation-grid">${sites.map((site,i)=>`<article class="card ${state.sites.includes(i)?'done':''}"><span class="eyebrow">SITE 0${i+1} / ${site.discipline}</span><h3>${site.name}</h3><p>${site.question}</p><small>△ ${site.risk||a.tags.join('・')}</small>${state.sites.includes(i)?'<p>✓ 観測済み</p>':btn(state.sites.length>=2?'代償を払い追加調査':'この問いを調べる','investigate',`data-site="${i}"`,'primary')}</article>`).join('')}</div>${state.sites.length>=2?`<div class="form-row">${select('payment','<option value="oxygen">酸素−1</option><option value="fatigue">担当の疲労+1</option>','3地点目の代償')}${btn('検証ボードを開く →','toHypothesis','','primary')}</div>`:'<p class="hint">あと '+(2-state.sites.length)+'つの問いを調べてください。</p>'}`;}
function deduction(){const a=anomaly(state),m=mystery(state),design=scenarioDesign(state),d=state.deduction||{},axes=design?.deduction||{trigger:a.hypotheses,nature:m.nature.options,response:m.response.options};const options=(items,selected)=>items.map((v,i)=>`<option value="${i}" ${selected===i?'selected':''}>${v}</option>`).join('');return `<h2>観測の差から、法則を組み立てる。</h2><p>どの記録なら説明でき、どの記録と矛盾するかを考えてください。ここでは答え合わせをしません。</p><div class="deduction-grid"><label class="inference-axis"><span>01 / 発生条件</span><strong>何が起きた時だけ現れる？</strong><select name="trigger">${options(axes.trigger,d.trigger)}</select></label><label class="inference-axis"><span>02 / 正体・目的</span><strong>第四の音は何を求めている？</strong><select name="nature">${options(axes.nature,d.nature)}</select></label><label class="inference-axis"><span>03 / 対処法</span><strong>どの条件を崩せばよい？</strong><select name="response">${options(axes.response,d.response)}</select></label></div><p class="hint">次に、あなたの仮説から実験結果を予測します。外れた予測も新しい観測として残ります。</p>${btn(state.experimentsDone?.length?'推理を更新して再実証へ →':'この仮説から結果を予測する →','deduce','','primary')}`;}
function verification(){const a=anomaly(state),m=mystery(state),design=scenarioDesign(state),d=state.deduction||{trigger:0,nature:0,response:0},axes=design?.deduction||{trigger:a.hypotheses,nature:m.nature.options,response:m.response.options},done=new Map((state.experimentResults||[]).map(r=>[r.id,r])),options=(items,selected)=>items.map((v,i)=>`<option value="${i}" ${selected===i?'selected':''}>${v}</option>`).join('');return `<div class="section-head"><div><span class="eyebrow">THEORY LAB / 検証ボード</span><h2>仮説を変えながら、結果を予測する。</h2></div><strong>${state.experimentsDone.length} / ${m.experiments.length} 実証</strong></div><p>観測の差を説明できる組み合わせを置き、実験結果を予測してください。予測の外れ方も次の推理材料になります。</p>${design?`<div class="deduction-grid live-theory"><label class="inference-axis"><span>01 / 発生条件</span><strong>何が起きた時だけ現れる？</strong><select name="trigger">${options(axes.trigger,d.trigger)}</select></label><label class="inference-axis"><span>02 / 正体・目的</span><strong>第四の音は何を求めている？</strong><select name="nature">${options(axes.nature,d.nature)}</select></label><label class="inference-axis"><span>03 / 対処法</span><strong>どの条件を崩せばよい？</strong><select name="response">${options(axes.response,d.response)}</select></label></div>`:`<div class="deduction-summary"><span>発生条件</span><b>${axes.trigger[d.trigger]}</b><span>正体</span><b>${axes.nature[d.nature]}</b><span>対処</span><b>${axes.response[d.response]}</b></div>`}${select('experimenter',crewOptions(),'実験担当')}<div class="cards experiment-grid">${m.experiments.map(exp=>{const result=done.get(exp.id),prediction=design?.predictions?.[exp.id];return `<article class="card ${result?'done':''}"><span class="eyebrow">EXPERIMENT</span><h3>${exp.name}</h3><p>${result?`<b>${result.predictionCorrect===null?'観測結果':result.predictionCorrect?'予測一致':'予測不一致'}</b><br>${result.result}`:exp.question}</p>${result?`${result.predictionText?`<small>予測：${result.predictionText}</small>`:''}<small>✓ 記録済み</small>`:`${prediction?select(`prediction-${exp.id}`,prediction.options.map((v,i)=>`<option value="${i}">${v}</option>`).join(''),'この仮説なら何が起こる？'):''}${btn(prediction?'この仮説で実験する':'この実験を行う','experiment',`data-id="${exp.id}"`,'primary')}`}</article>`;}).join('')}</div>${state.experimentResults.length?`<div class="case-file">${state.experimentResults.map(r=>`<p><b>${r.predictionCorrect?'○':'△'} ${r.name}</b>${r.result}</p>`).join('')}</div>`:''}<div class="commit-decision"><p><strong>最終決断へ進むと、仮説の修正や追加実験はできません。</strong><br>まだ確かめたいことがあれば、上の別の実験を選んでください。</p>${btn('この記録で最終決断へ →','toCrisis',`${state.experimentsDone?.length?'':'disabled'}`,'primary')}</div>`;}
function crisis(){const m=mystery(state),design=scenarioDesign(state),available=m.outcomes.filter(out=>outcomeAvailable(state,out)),shown=design?available:m.outcomes;return `<h2>戻れない決断をする。</h2><p>${design?'観測と実証から到達できた対応だけが残っています。ここで選んだ行動が、この事案の結末になります。':'実証は終わった。何を知り、何を持ち帰り、何を船内へ残すか決める。'}</p><div class="insight-meter"><span>調査記録</span><strong>観測 ${visibleClues(state).length}件</strong><small>実証 ${state.experimentsDone.length}件${design?` / 予測一致 ${correctPredictionCount(state)}件`:''}</small></div>${design&&state.experimentResults.length?`<div class="case-file">${state.experimentResults.map(r=>`<p><b>${r.predictionCorrect?'○':'△'} ${r.name}</b>${r.result}</p>`).join('')}</div>`:''}<div class="cards outcome-grid">${shown.map(out=>`<article class="card"><span class="eyebrow">FINAL DECISION</span><h3>${out.name}</h3><p>この選択の結果は確定するまで分からない。</p>${btn('この道を選ぶ','outcome',`data-id="${out.id}"`,'primary')}</article>`).join('')}</div>`;}
function aftermath(){const out=state.mysteryOutcome;return `<section class="ending-card"><span class="eyebrow">ANOMALY ENDING / 個別結末</span><h2>${out.name}</h2><p class="lead">${out.text}</p>${out.reveal?`<div class="truth"><span>判明した正体</span><p>${out.truth}</p></div>`:'<div class="truth unresolved"><span>未解明</span><p>法則の一部だけを持ち帰った。正体は記録の外に残っている。</p></div>'}<p>この異常の結末は航海記録へ保存されます。</p>${btn(anomaly(state).id==='F01'?'浮上を開始する →':state.focusScenario?'調査報告へ →':'航路判断へ →','continue','','primary')}</section>`;}
function hypothesis(){const a=anomaly(state);return `<h2>何が、この異常を動かすのか。</h2><p>選択した法則は遭遇が終わるまで判定されません。</p><div class="hypotheses">${a.hypotheses.map((h,i)=>`<article class="card"><label><input type="radio" name="hypothesis" value="${i}"><strong>${h}</strong></label><label class="muted">関連づける証拠<select name="link${i}"><option value="">指定しない</option>${state.clues.map(k=>`<option value="${k}">証拠${k+1}：${a.clues[k]}</option>`).join('')}</select></label></article>`).join('')}<label class="choice"><input type="radio" name="hypothesis" value="unknown" checked>分からない <small>補正・罰則なし</small></label></div><p class="hint">正解：有利解法+2 / 誤り：汚染+1、最初の異常行動が即時発動</p>${btn('仮説を確定して配置へ →','hypothesis','','primary')}`;}
function preparation(){return `<p class="hint">仮説：${state.hypothesis===null?'分からない':anomaly(state).hypotheses[state.hypothesis]}${state.hypothesis!==null&&state.links[state.hypothesis]!==''&&state.links[state.hypothesis]!==undefined?' / 関連証拠 '+(Number(state.links[state.hypothesis])+1):''}</p>${board()}<details open><summary>配置による命令予測</summary>${commandCards(false)}</details>${btn('準備完了 — 遭遇へ →','ready','','primary')}`;}
function encounter(){const e=state.encounter;return `<div class="section-head"><h2>${anomaly(state).name}</h2><strong>TURN ${e.turn} / 6</strong></div><p class="intent">${intent(state).text}</p>${state.flags.core==='connect'?'<p class="hint">予知接続中</p>':''}<div class="progress-grid">${Object.entries(MODES).map(([id,name])=>meter(name,Math.min(e.progress[id],e.targets[id]),e.targets[id])).join('')}</div><div class="actions">${capable(state.crew.find(c=>c.id==='aoi'))&&!state.flags.aoiUsed&&state.clues.length<3?btn('アオイ：未取得の手掛かりを読む','clue'):''}${state.undo?btn('直前の命令を選び直す','rewind'):''}</div>${select('healTarget',crewOptions(true),'応急処置の対象')}${commandCards()}<details><summary>現在の船内配置を確認</summary>${board(false)}</details>${anomaly(state).id==='F01'&&!e.moved?`<div class="form-row">${select('moveCrew',crewOptions(),'未来を外す隊員')}${select('moveModule',MODULES.map((m,i)=>`<option value="${i}">${m.name}</option>`).join(''),'移動先')}${btn('配置変更で未来記録を外す（1回）','reposition')}</div>`:''}`;}
function reward(){return `<h2>法則を、記録した。</h2><p class="law">「${anomaly(state).hypotheses[anomaly(state).correct]}」</p><p>${state.hypothesis===null?'仮説なし':state.hypothesis===anomaly(state).correct?'✓ 仮説は正しかった':'△ 仮説と異なっていた'} / 解法：${MODES[state.resolution]||'撤退'}</p>${state.undo?btn('時間を戻して命令を選び直す','rewind'):''}<div class="form-row">${select('rewardTarget',crewOptions(true),'治療対象')}${select('treatment','<option value="fatigue">疲労−2</option><option value="hp">体力+1</option>','治療方法')}</div>${state.relics.length===4?select('replace',state.relics.map(id=>`<option value="${id}">${RELICS.find(r=>r.id===id).name}</option>`).join(''),'遺物庫満杯：交換して手放す遺物'):''}<div class="cards">${state.rewards.map(r=>{const relic=RELICS.find(v=>v.id===r.relic);return `<article class="card"><h3>${r.name}</h3><p>${relic?`＋ ${relic.benefit}<br>△ ${relic.side}`:'帰還のために、資源と知識を整える。'}</p>${btn('この報酬を選ぶ','reward',`data-id="${r.id}"`,'primary')}</article>`;}).join('')}</div>`;}
function decision(){const next=ENVIRONMENTS[Math.min(4,Math.floor(state.completed/2)+1)];return `<h2>さらに深く。あるいは、帰還。</h2><div class="decision-grid"><article class="card"><span class="eyebrow">DESCEND</span><h3>${state.completed>=6?'ミナモへ到達する':state.completed===2&&!state.safeUsed?'安全域を経て下降する':next.place}</h3><p>次の危険：${next.tags.join(' / ')}<br>${next.rule}</p>${btn('下降を続ける →','descend','','primary')}</article><article class="card"><span class="eyebrow">ASCEND</span><h3>帰還の見通し：${returnRisk(state)}</h3><p>現在の調査点 ${state.score}<br>浮上後は2回の代償イベント。<br>${state.flags.core?'記録核を確保済み':'記録核は未回収。任務は未達。'}</p>${btn('浮上を開始する ↑','ascend')}</article></div>${state.resolution==='retreat'?`<p class="law">撤退時に確認した法則：${anomaly(state).hypotheses[anomaly(state).correct]}</p>`:''}<p class="story">${['','第一断片：ミナモは、異常生物に襲われた。','第二断片：私たちは何かを、船へ招き入れた。','第三断片：この記録の日付は、カイロス7出航の翌日だ。'][Math.min(3,state.depth)]}</p>`;}
function safe(){return `<h2>海が、静かになった。</h2><p>ここで一度だけ、船か隊員を整えられる。</p>${select('safeTarget',crewOptions(true),'休息・治療する隊員')}<div class="actions">${btn('船体を修理する +2','safe','data-id="repair"')}${btn('隊員を治療する 体力+1','safe','data-id="hp"')}${btn('隊員を休ませる 疲労−2','safe','data-id="fatigue"')}</div>`;}
function event(){const opts=eventOptions(state);return `<h2>${state.node.event===null?'船内通信':eventNames()[state.node.event]}</h2><p>通信回線が開いた。返答を待っているのは、誰だろう。</p><div class="cards">${opts.map(o=>`<article class="card"><h3>${o.name}</h3><p>${o.text}</p>${btn(o.id===3?'特別対応を選ぶ':'対応を選ぶ','event',`data-choice="${o.id}"`)}</article>`).join('')}</div>`;}
function eventNames(){return ['救難信号は船内から','食事が一人分多い','名前のない隊員名簿','外殻を叩く規則音','漂流する自分たちの廃棄物','深海の診察券'];}
function core(){return `<h2>記録核には、明日がある。</h2><p>まだ実行していない浮上事故が、記録されている。持ち帰れば、それも現実になるのだろうか。</p><div class="cards">${[['recover','記録核を回収する','調査点+5 / 正規任務達成へ / 浮上の損害増加'],['destroy','記録核を破壊する','調査点−2 / 浮上の代償が軽減'],['connect','記録核を船へ接続する','汚染+3 / 未来予測 / 反復の結末へ']].map(([id,name,text])=>`<article class="card"><h3>${name}</h3><p>${text}</p>${btn('この処置を実行','core',`data-id="${id}"`)}</article>`).join('')}</div>`;}
function ascent(){return `<h2>${['浮上 I — 遺物の共鳴','浮上 II — 記憶の混線','時間共鳴 — 余分な一秒'][state.ascentStep]}</h2><p>${state.ascentStep===0?'船内の物体が、船体の外から響いている。何かを切り離さなければならない。':'海面の呼出信号が、昨日の声で聞こえる。自分たちを現在へつなぎとめる。'}</p><div class="form-row">${select('ascentCrew',crewOptions(),'代償を引き受ける隊員')}${select('ascentRelic',state.relics.map(id=>`<option value="${id}">${RELICS.find(r=>r.id===id).name}</option>`).join('')||'<option>遺物なし</option>','切り離す遺物')}</div><div class="cards">${ascentOptions(state).map(o=>`<article class="card"><h3>${o.name}</h3><p>${o.text}</p>${btn('代償を選ぶ','ascentChoice',`data-id="${o.id}" ${o.disabled?'disabled':''}`)}</article>`).join('')}</div><details><summary>浮上中の装備を変更</summary>${board()}</details>`;}
function result(){const focused=!!state.focusScenario,endings={return:focused?['調査完了',state.mysteryOutcome?.text||'四人目の呼吸に関する記録を持ち帰った。']:['帰還',state.flags.core==='recover'?'記録核を抱え、カイロス7は海面へ浮かんだ。管制塔から、ミナモと同じ信号が届く。':'記録核には届かなかった。それでも、持ち帰った観測が次の航路を照らす。'],empty:['空の帰還','記録核は海底に砕けた。局は任務失敗と記した。生きて戻った者には、別の答えがあった。'],loop:['反復','海面に出た瞬間、日付が出航日に戻った。次の調査の記録には、すでに未来の一文がある。'],loss:['喪失','最後の調査記録だけが、記録局へ届いた。深海からの信号には、まだ三人の声が混ざっている。']};const [name,text]=endings[state.ending];return `<main class="result panel">${small(focused?'CASE REPORT / 重点調査終了':'EXPEDITION REPORT / 調査終了')}<h1>${name}</h1>${sceneArt(focused?SCENES.anomalies[state.focusScenario]:SCENES.splash)}<p class="lead">${text}</p>${state.lossReason?`<p class="warning">喪失原因：${state.lossReason}</p>`:''}${focused?'<p>「四人目の呼吸」の観測・推理・結末を記録しました。</p>':`<p>${state.flags.core==='recover'&&state.ending!=='loss'?'✓ 記録核回収・海面帰還：任務成功':'記録核回収任務：未達'}</p>`}${focused?fieldReturnReport():''}<div class="report"><span>到達深度<strong>${state.bestDepth===4?'最深部':state.bestDepth}</strong></span><span>調査点<strong>${state.score}</strong></span><span>${focused?'重点調査':'通常調査'}<strong>${focused?'1 / 1':state.completed+' / 6'}</strong></span></div><h3>調査した異常</h3><p>${[...new Set(state.records.map(r=>r.name))].join(' / ')||'なし'}</p><h3>${state.ending==='loss'?'深海に残されたもの':'回収したもの'}</h3><p>${[...(state.field?.values.container==='occupied'?['密封した呼吸マスク']:[]),...state.relics.map(id=>RELICS.find(r=>r.id===id).name)].join(' / ')||'なし'}</p><h3>今回の図鑑追加</h3><p>${state.newDiscoveries?.join(' / ')||'なし（既知の記録を更新）'}</p><div class="cards">${state.crew.map(c=>`<article class="card"><b>${c.name}</b><p>体力${c.hp} / 疲労${c.fatigue}<br>${active(c)?'活動可能':'行動不能'}</p></article>`).join('')}</div><p class="muted">SEED: ${escape(state.seed)}${state.ending==='loop'?' / 日付：出航日':''}</p><div class="actions">${btn(focused?'同じ条件で再調査 →':'同じシードで再挑戦 →','retry','data-mode="same"','primary')}${btn(focused?'新しく再調査 →':'新しい海域へ →','retry','data-mode="new"')}${btn('タイトルへ','title')}</div></main>`;}
let fieldTarget='sensor',compareIds=[];
function fieldSituation(){
 const f=state.field,v=f.values,remaining=state.oxygen-2;
 const pressure=f.pressure||0;
 const title=pressure>=3?'隔壁がきしむ。次の接触が危ない。':pressure>=2?'呼吸が、こちらの拍を追い始めた。':pressure===1?'もう一つの呼吸が応じている。':'まだ、回線は静かだ。';
 const gains=[f.records.some(r=>r.measurement)?'観測記録':'',v.contact==='named'?'冬城ユラの名前':v.contact==='heard'?'途切れた声':'',v.container==='occupied'?'呼吸する標本':''].filter(Boolean);
 return `<section class="field-situation ${pressure>=3||remaining<2?'is-critical':''}" aria-label="現場の危険と帰還判断"><div><span class="eyebrow">CONTACT / 現場の反応</span><h2>${title}</h2><div class="pressure-track" aria-label="反応圧 ${pressure}。4で配管破裂">${[1,2,3,4].map(i=>`<i class="${i<=pressure?'lit':''} ${i===4?'breakpoint':''}">${i===4?'破裂':i}</i>`).join('')}</div><p>接触で圧が増す。4に達すると配管破裂：船体 −4・酸素 −1。呼吸が船室へ漏れ、圧は2に戻る。測定・比較・配置変更では進まない。</p></div><div class="return-budget"><span>浮上に残す酸素</span><strong>2 <small>/ 現在 ${state.oxygen}</small></strong><p class="${remaining<0?'warning':''}">${remaining<0?'酸素不足。今のまま浮上すると帰還できない。':`調査に使える余裕：${remaining}。浮上で酸素2を使う。`}</p><span>いま確保したもの</span><p>${gains.join(' / ')||'まだ観測記録なし'}</p></div></section>`;
}
function fieldReturnReport(){
 if(!state.field)return '';
 const f=state.field,v=f.values;
 const facts=[v.contact==='named'?'名前と点呼を求める声を記録':v.contact==='heard'?'途切れた声を記録':'名前は未確認',v.container==='occupied'?(state.ending==='loss'?'標本は深海に残された':'呼吸する標本を確保'):v.container==='released'?'標本を手放した':'標本は未回収',f.breaches?`配管破裂 ${f.breaches}回 / 船体 ${state.hull}/12`:'配管破裂なし',`残り酸素 ${state.oxygen}/10`];
 return `<section class="field-return-report"><h2>${state.ending==='loss'?'深追いの帰結':'今回、引き受けたもの'}</h2><ul>${facts.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><p>安全に分離する、名前を聞く、標本を持ち帰る。それぞれ別の成果です。</p></section>`;
}
function fieldView(){
 const design=FIELD_SCENARIOS[state.node.anomaly],field=state.field;
 const targets=[...design.targets.filter(t=>matches(field.values,t.requires)),{id:'operations',name:'対処',text:'準備した条件で実際に操作します。下の実行ボタンを押し、その後で測り直してください。作戦の保存だけでは現場は変わりません。'}];
 const target=targets.find(t=>t.id===fieldTarget)||targets[0];
 const operations=target.id==='operations';
 const actions=design.actions.filter(a=>operations?(a.intervention||Object.keys(a.set||{}).some(k=>(design.operationConditions||[]).includes(k))):a.target===target.id),groups=new Map();
 for(const action of actions.filter(a=>!a.final)){
  const condition=!action.warning&&action.set&&design.conditions.find(c=>Object.hasOwn(action.set,c.key));
  const key=condition?.key||(action.intervention?'intervene':'observe');
  if(!groups.has(key))groups.set(key,{label:condition?.label||(action.intervention?'実行・対処':'観測・確認'),condition,actions:[]});
  groups.get(key).actions.push(action);
 }
 for(const group of groups.values()){
  if(!group.condition)continue;
  const order=Object.keys(group.condition.options);
  group.actions.sort((a,b)=>order.indexOf(String(a.set[group.condition.key]))-order.indexOf(String(b.set[group.condition.key])));
 }
 const control=(a,condition)=>{
  const selected=!!condition&&!!a.set&&Object.entries(a.set).every(([k,v])=>field.values[k]===v);
  const label=condition?condition.options[a.set[condition.key]]:a.label;
  const missing=!matches(field.values,a.requires)||(a.id==='cool'&&!(field.pressure>0))||(a.id==='supply'&&state.oxygen>8);
  const risk=fieldActionRisk(field,design,a.id),after=Math.min(10,state.oxygen-risk.oxygen);
  const oxygenLabel=`酸素 ${risk.oxygen<0?'+':'−'}${Math.abs(risk.oxygen)}`;
  const forecast=a.final?`浮上で酸素 −2。${state.oxygen<2?'不足：帰還できません。':'現在の成果を持ち帰れます。'}`:risk.oxygen||risk.delta?`${oxygenLabel}${risk.hull?` / 船体 −${risk.hull}`:''}${risk.delta?` / 反応圧 ${field.pressure||0} → ${risk.pressure}`:''}${risk.breach?' / 配管破裂・船室へ漏出':''}${state.hull<=risk.hull?' / 船体崩壊・喪失':after<2?' / 浮上用酸素が足りなくなる':''}`:'';
  const requirement=missing?(a.id==='supply'&&state.oxygen>8?'酸素8以下で利用できます。タンクの容量を超える供給はできません。':a.id==='cool'&&!(field.pressure>0)?'反応圧は0です。冷却は不要です。':a.requirementText||'現在の状態では実行できません。'):'';
  const purpose=a.id==='call'?(field.values.pulse==='long'?'途切れた声の続きを追う':'短い応答を探る'):a.id==='cool'?'声の記録と標本を残して、圧を下げる':a.id==='recover'?'標本を持ち帰る。容器は一つだけ':a.id==='supply'?'船体を犠牲に、調査と帰還の余裕を作る':'';
  return `<div class="field-control-item">${btn(`${selected?'<span aria-hidden="true">● </span>':''}${escape(label)}${risk.oxygen?` <small>${oxygenLabel}</small>`:''}`,'fieldAction',`data-id="${a.id}" ${condition?`aria-pressed="${selected}"`:''} ${missing?'disabled':''}`,selected?'is-on':a.final?'field-final':'')}${purpose?`<small class="field-purpose">${escape(purpose)}</small>`:''}${forecast?`<small class="field-forecast ${risk.breach||after<2?'hazard':''}">${escape(forecast)}</small>`:''}${requirement?`<small class="field-requirement">${escape(requirement)}</small>`:''}</div>`;
 };
 const finalActions=design.actions.filter(a=>a.final);
 return `<section class="field-workbench ${operations?'is-operations':''}"><nav aria-label="調べる対象">${targets.map(t=>btn(t.name,'fieldTarget',`data-id="${t.id}" aria-pressed="${t.id===target.id}"`,t.id===target.id?'is-on':'')).join('')}${btn('記録を比較','fieldJournal')}</nav><p class="field-target-description">${escape(target.text)}</p>${operations?`<div class="operation-shortcuts"><span>準備・結果の確認</span>${targets.filter(t=>!['operations'].includes(t.id)).map(t=>btn(t.name,'fieldTarget',`data-id="${t.id}"`)).join('')}</div>`:''}<div class="field-conditions">${design.conditions.map(c=>`<span>${c.label}<b>${escape(c.options[field.values[c.key]])}</b></span>`).join('')}</div><div class="field-operation-layout"><div class="field-controls">${[...groups.values()].map(g=>`<fieldset class="field-control-group ${g.condition?'':'field-action-group'}"><legend>${escape(g.label)}</legend><div>${g.actions.map(a=>control(a,g.condition)).join('')}</div></fieldset>`).join('')}</div>${finalActions.length?`<aside class="field-departure"><span>作戦と撤収</span>${btn('作戦を組む','fieldPlan')}${btn('対処を実行する →','fieldTarget','data-id="operations"','is-on')}<p class="field-departure-hint">${escape(field.plan?.goal||'何を変えたいか、観測記録を根拠に考える。')}<br>${field.plan?.evidence?.length?`根拠：${field.plan.evidence.map(id=>'#'+id).join('・')}`:''}</p><p class="field-departure-hint">声を追えば名前に近づく。標本を回収すれば持ち帰れる。残す酸素と次の反応を比べて、踏み込む範囲を決める。</p>${finalActions.map(a=>control(a)).join('')}</aside>`:''}</div><p class="muted">確認・測定・比較は無料。呼吸合図・通信・回収で酸素と反応圧が変わります。冷却弁は酸素2で圧を2下げます。緊急供給は一度だけ、船体3と引き換えに酸素2。考えている間に危険は進みません。</p></section>`;
}
function fieldJournal(){
 const records=state.field.records.filter(r=>r.measurement||r.action==='inspect');
 const chosen=compareIds.map(id=>records.find(r=>r.id===id)).filter(Boolean);
 showDialog('観測記録を比較',`<p>比べたい記録を二つ選択。観測した事実だけが残ります。</p><div class="field-record-picks">${records.map(r=>btn(`#${r.id} ${escape(r.label)}`,'compareRecord',`data-id="${r.id}" aria-pressed="${compareIds.includes(r.id)}"`,compareIds.includes(r.id)?'primary':'')).join('')||'<p>集音器で測定するか、区画のマスクを確認してください。</p>'}</div><div class="field-comparison">${[0,1].map(i=>{const r=chosen[i];return r?`<article><h3>記録 #${r.id}</h3><dl>${Object.entries(r.conditions).map(([k,v])=>`<div><dt>${escape(k)}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl><p>${escape(r.text)}</p></article>`:'<article class="field-record-empty" aria-label="未選択の比較欄"><p>比較する記録を選択</p></article>';}).join('')}</div>`,null,'field-journal');dialog.querySelector('.actions').insertAdjacentHTML('afterbegin',btn('選んだ記録で作戦を組む','fieldPlan')); 
}

function render(){
 document.body.classList.toggle('reduced',settings.reduced);
 document.body.dataset.depth=state?.depth||1;
 document.body.dataset.screen=screen==='game'&&state?.phase==='result'?'result':screen;
 document.body.dataset.phase=state?.phase||'';
 let html=header();
 if(screen==='title')html+=title();
 else if(screen==='launch')html+=launch();
 else if(state.phase==='result')html+=result();
 else if(state.phase==='investigation'&&state.flags.introPending)html+=scenarioIntro();
 else{
  const env=ENVIRONMENTS[state.depth],scenario=scenarioSummary();
  const phaseView=({route,investigation,deduction,verification,crisis,aftermath,hypothesis,preparation,encounter,reward,decision,safe,event,core,ascent}[state.phase])();
  html+=`<div class="mission-bar"><div class="mission-left"><div class="mission-stat mission-depth"><span>DEPTH</span><strong>${state.depth} / ${env.meters} M</strong></div><div class="mission-stat mission-phase"><span>PHASE</span><strong>${state.field&&state.phase==='investigation'&&state.field.stage==='aftercare'?'対処後の確認':phases[state.phase]}</strong></div></div><div class="mission-scenario"><strong>${escape(scenario.title)}</strong><p>${escape(scenario.text)}</p></div><span class="mission-seed">SEED ${escape(state.seed)}</span></div><div class="vital-strip" aria-label="現在の潜航状態">▰ 船体 ${state.hull}/12　◉ 酸素 ${state.oxygen}/10　※ 汚染 ${state.contamination}/8　● 活動 ${state.crew.filter(active).length}/3</div><div class="workspace"><aside class="context panel">${small(state.focusScenario?'FOCUS CASE / 重点調査':'MISSION / 作戦目標')}<h2>${state.field?'何を<br>持ち帰る？':state.focusScenario?'四人目の呼吸を<br>解明せよ':'ミナモの<br>記録核を回収せよ'}</h2><p>${state.focusScenario&&state.phase==='route'?'調査条件を確認し、この事案へ進んでください。':state.field?(state.phase==='aftermath'?'帰還しました。現場を離れた時の状態と持ち帰った成果を確認してください。':state.field.stage==='aftercare'?'対処前と今を比べてください。何が残ったかを確かめ、接触・回収・撤収を判断します。':'調べる対象を選び、条件を変えて測定。記録の違いから次の一手を考えてください。'):objectives[state.phase]}</p>${state.focusScenario?'<div class="depth-track"><span class="current">A07</span></div><p class="muted">対象を選ぶ → 条件を変える → 測る → 比べる。</p>':`<div class="depth-track">${[1,2,3,4].map(i=>`<span class="${state.depth===i?'current':''}">${i===4?'核':i}</span>`).join('')}</div><p class="muted">${env.rule}</p>`}${clues()}</aside><main class="content panel" tabindex="-1">${sceneArt(sceneForState(),'',sceneNarration())}${phaseView}</main>${status()}</div>`;
 }
 app.innerHTML=html;
 startNarration();
}
function showDialog(title,body,action,kind=''){dialog.className=kind;pending=action||null;dialog.innerHTML=`<h2>${escape(title)}</h2>${body}<div class="actions">${action?btn('確定する','confirm','','primary'):''}${btn(action?'取り消す':'閉じる','close')}</div>`;dialog.showModal();}
function confirm(title,text,action){if(action&&state)action.revision=state.revision||0;showDialog(title,`<p>${escape(text)}</p>`,action);}
function dispatch(action){try{const focused=document.activeElement;const focusKey=focused?.dataset?.action?{action:focused.dataset.action,module:focused.dataset.module,id:focused.dataset.id}:null;const before=state;state=reduce(state,action);if(state===before)return; if(state.phase==='result'){state.newDiscoveries=[...new Set(state.records.filter(r=>!meta.discoveries[r.id]).map(r=>r.name))];meta=updateMeta(meta,state);tone('result');}else tone(state.hull<before.hull?'damage':action.type==='INVESTIGATE'?'sonar':'success');persist();render();$('#announcer').textContent=state.history.at(-1)?.summary||phases[state.phase]; if(before.phase!==state.phase){$('main')?.focus();window.scrollTo(0,0);}else if(focusKey){const control=Array.from(document.querySelectorAll('[data-action]')).find(el=>el.dataset.action===focusKey.action&&el.dataset.module===focusKey.module&&el.dataset.id===focusKey.id&&!el.disabled);(control||$('main'))?.focus();}}catch(e){showDialog('操作を完了できません',`<p>${escape(e.message)}</p>`);}}
function freshSeed(){const a=new Uint32Array(2);crypto.getRandomValues(a);return `KN-${a[0].toString(36).toUpperCase()}-${a[1].toString(36).slice(0,3).toUpperCase()}`;}
function start(seed,tool){state=newRun(seed||freshSeed(),tool,FOCUS_SCENARIO);state.sessionId=crypto.randomUUID();fieldTarget='sensor';compareIds=[];lastNarrationKey='';screen='game';persist();render();window.scrollTo(0,0);}
const value=name=>document.querySelector(`[name="${name}"]`)?.value;
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.config){const i=Number(el.dataset.module);if(el.dataset.config==='crew')dispatch({type:'ASSIGN',module:i,crew:el.value});else confirm('遺物接続を変更',el.value?'接続するとレンの疲労+1。遺物固有の副作用も発生します。':'この設備の遺物を取り外します。',{type:'EQUIP',module:i,id:el.value});}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;e.preventDefault();tone();const id=b.dataset.id;switch(b.dataset.action){
 case 'fieldTarget':fieldTarget=id;render();break;
 case 'fieldJournal':compareIds=state.field.records.filter(r=>r.measurement||r.action==='inspect').slice(-2).map(r=>r.id);fieldJournal();break;
 case 'compareRecord':{const scroll=dialog.querySelector('.field-record-picks')?.scrollTop||0;const n=Number(id);compareIds=compareIds.includes(n)?compareIds.filter(x=>x!==n):[...compareIds.slice(-1),n];fieldJournal();dialog.querySelector('.field-record-picks').scrollTop=scroll;dialog.querySelector(`[data-action="compareRecord"][data-id="${n}"]`)?.focus({preventScroll:true});break;}
 case 'fieldPlan':{const d=FIELD_SCENARIOS[state.node.anomaly],records=state.field.records.filter(r=>r.measurement),evidence=compareIds.filter(id=>records.some(r=>r.id===id));showDialog('作戦を組む',`<p>記録は根拠として残します。正解は採点されません。実際の対処で確かめてください。</p>${select('planGoal',d.goals.map(g=>`<option ${state.field.plan?.goal===g?'selected':''}>${escape(g)}</option>`).join(''),'今回の狙い')}<div class="plan-evidence">${records.map(r=>`<label><input type="checkbox" name="planEvidence" value="${r.id}" ${(evidence.length?evidence:state.field.plan?.evidence||[]).includes(r.id)?'checked':''}> #${r.id} ${escape(r.text)}</label>`).join('')||'<p>まだ測定記録はありません。根拠なしでも作戦を設定できます。</p>'}</div><p class="muted">根拠は最大二つ。作戦を保存しても配置や現場の状態は変わりません。</p>${btn('作戦を保存して対処へ →','saveFieldPlan','','primary')}`);break;}
 case 'saveFieldPlan':{const evidence=[...dialog.querySelectorAll('[name="planEvidence"]:checked')].map(el=>Number(el.value));if(evidence.length>2){const note=dialog.querySelector('.muted');note.textContent='根拠は二つ以内にしてください。';break;}const goal=value('planGoal');dialog.close();fieldTarget='operations';dispatch({type:'FIELD_PLAN',goal,evidence});break;}
 case 'fieldAction':{const design=FIELD_SCENARIOS[state.node.anomaly],action=design.actions.find(a=>a.id===id),risk=fieldActionRisk(state.field,design,id),after=Math.min(10,state.oxygen-risk.oxygen);
 const forecast=`酸素 ${risk.oxygen<0?'+':'−'}${Math.abs(risk.oxygen)}。${risk.hull&&!risk.breach?`船体 −${risk.hull}。`:''}${risk.delta?`反応圧 ${state.field.pressure||0} → ${risk.pressure}。`:''}${risk.breach?'配管が破裂し、船体 −4。呼吸が船室へ漏れます（酸素の表示は漏出1を含む）。':''}${state.hull<=risk.hull?'船体が崩壊し、喪失します。':!action.final&&after<2?'浮上用の酸素2を残せません。':''}`;
 if(action.final||action.warning||risk.breach||after<2)confirm(action.label,`${action.final?(state.oxygen<2?'酸素が足りず、浮上途中で喪失します。':'浮上に酸素2を使い、現在の成果で帰還します。')+'追加の調査には戻れません。':action.warning||'この接触を実行します。'} ${forecast}`,{type:'FIELD_ACTION',id});else dispatch({type:'FIELD_ACTION',id});break;}

 case 'launch':if(saved&&saved.phase!=='result')showDialog('新しい調査を開始', '<p>進行中のランを上書きします。調査記録は残ります。</p>',()=>{screen='launch';render();});else{screen='launch';render();}break;
 case 'title':dialog.close();screen='title';render();break;
 case 'start':start(freshSeed(),'silent');break;
 case 'resume':state=structuredClone(saved);screen='game';render();break;
 case 'retry':start(b.dataset.mode==='same'?state.seed:freshSeed(),state.tool);break;
 case 'sound':settings.sound=!settings.sound;persist();render();tone();break;
 case 'motion':settings.reduced=!settings.reduced;persist();render();break;
 case 'help':showDialog('深淵異常調査船の遊び方',`<p>乗員は三人。記録された呼吸は、四人分。観測した違いを手がかりに、怪異の法則を探ります。</p><ol class="help-steps"><li><h3>調査を始める</h3><p>「調査を開始」→「重点調査を開始」から紹介を読み、「調査へ進む」。続きがある場合は「前回の調査を再開」を選べます。</p></li><li><h3>条件を変えて、測る</h3><p>集音器・協力者・録音機・隔離区画を選んで調べます。配置や条件を変え、集音器で「十秒間を測定・保存」。確認・測定・比較に資源の消費はありません。</p></li><li><h3>記録を比べて、対処を試す</h3><p>「記録を比較」で二つの観測を並べ、「作戦を組む」で狙いと根拠を残します。作戦の保存だけでは現場は変わりません。対処のボタンで実際に操作し、もう一度測って変化を確かめましょう。</p></li><li><h3>現場を離れる</h3><p>調べ終えたら「この現場を離れて浮上」。残した状態や得た応答で結末が変わります。酸素を使う処置や取り消せない操作は、画面の説明を確認してください。</p></li></ol><p>現在は「四人目の呼吸」一件を収録した試作版です。PCブラウザ推奨・ホラー表現あり。</p><p>操作時に自動保存されます。同じブラウザで再開できますが、ブラウザのデータを消すと記録も消えます。接触で反応圧が4になると配管破裂（船体−4・酸素−1）。冷却弁は酸素2で圧を2下げます。浮上には酸素2が必要です。音と動きは画面上部で切り替えられます。</p><p>Tabで移動／Enter・Spaceで決定／Escで閉じる。</p>`,null,'game-help');dialog.querySelector('h2').setAttribute('tabindex','-1');dialog.querySelector('h2').focus({preventScroll:true});dialog.scrollTop=0;break;
 case 'settings':showDialog('設定',`<p>音：${settings.sound?'ON':'OFF'} / 動き：${settings.reduced?'OFF':'ON'}<br>ヘッダーのボタンで切り替えられます。</p><p>Tabで移動 / Enter・Spaceで決定 / Escで閉じる。<br>選択は確認画面で取り消せます。</p>${saveError?`<p class="warning">${escape(saveError)}</p>`:''}`);break;
 case 'archive':showDialog('調査記録',`<p>ベスト深度 ${meta.bestDepth} / 最高調査点 ${meta.bestScore} / 帰還 ${meta.returns}回</p>${Object.values(meta.discoveries).map(d=>`<h3>${escape(d.name)}</h3><p>${escape(d.law)}</p>${d.endings?.length?`<small>確認した個別結末：${d.endings.map(escape).join(' / ')}</small>`:''}`).join('')||'<p>未知の海です。法則を持ち帰ってください。</p>'}<p>到達した航海結末：${meta.endings.map(e=>({return:'帰還',empty:'空の帰還',loop:'反復',loss:'喪失'}[e])).join(' / ')||'なし'}</p>`);break;
 case 'route':confirm('航路を確定','到着時に酸素を1消費します。',{type:'SELECT_ROUTE',id});break;
 case 'investigate':{const extra=state.sites.length>=2;confirm('調査を実行',extra?`追加調査：${value('payment')==='fatigue'?'担当隊員の疲労+1':'酸素−1'}。接触標本は適性・道具なしで船体−1。`:'担当隊員と道具を使って観測します。接触標本は適性・道具なしで船体−1。',{type:'INVESTIGATE',site:Number(b.dataset.site),crew:value('investigator'),tool:value('investTool')==='yes',payment:value('payment')});break;}
 case 'toHypothesis':dispatch({type:'TO_HYPOTHESIS'});break;
 case 'deduce':dispatch({type:'DEDUCE',trigger:Number(value('trigger')),nature:Number(value('nature')),response:Number(value('response'))});break;
 case 'experiment':{const exp=mystery(state).experiments.find(x=>x.id===id),prediction=scenarioDesign(state)?.predictions?.[id],predictionValue=prediction?Number(value(`prediction-${id}`)):undefined,deduction=prediction?{trigger:Number(value('trigger')),nature:Number(value('nature')),response:Number(value('response'))}:undefined;confirm('仮説と予測を固定して実験',prediction?`予測：「${prediction.options[predictionValue]}」　${exp.question}`:exp.question,{type:'EXPERIMENT',id,target:value('experimenter'),prediction:predictionValue,deduction});break;}
 case 'revise':dispatch({type:'REVISE'});break;
 case 'toCrisis':dispatch({type:'TO_CRISIS'});break;
 case 'outcome':confirm('この決断を確定',mystery(state).outcomes.find(x=>x.id===id).name+'。この異常の結末が変化します。',{type:'OUTCOME',id,target:value('experimenter')});break;
 case 'continue':dispatch({type:'CONTINUE'});break;
 case 'hypothesis':{const h=document.querySelector('[name="hypothesis"]:checked').value;confirm('仮説を固定',h==='unknown'?'補正も罰も受けずに準備へ進みます。':anomaly(state).hypotheses[Number(h)],{type:'HYPOTHESIS',value:h==='unknown'?null:Number(h),links:Object.fromEntries([0,1,2].map(i=>[i,value('link'+i)]))});break;}
 case 'power':dispatch({type:'POWER',module:Number(b.dataset.module),amount:Number(b.dataset.amount)});break;
 case 'ready':confirm('準備完了','遭遇中は通常の配置変更ができません。誤仮説の場合、汚染+1と異常の即時行動。',{type:'READY'});break;
 case 'command':{const p=commandPreview(state,id);confirm(p.name,`${p.mode?MODES[p.mode]+' +'+p.value+' / ':''}電力${p.cost}。${p.extra||'追加コストなし'}。未解決なら異常が行動します。`,{type:'COMMAND',id,target:value('healTarget')});break;}
 case 'clue':dispatch({type:'CLUE'});break;
 case 'rewind':confirm('命令を選び直す','昨日の時計は酸素−1。時間共鳴のみなら酸素消費なし。',{type:'REWIND'});break;
 case 'reposition':dispatch({type:'REPOSITION',crew:value('moveCrew'),module:Number(value('moveModule'))});break;
 case 'reward':confirm('報酬を確定',state.rewards.find(r=>r.id===id).name+(id.startsWith('relic:')&&state.relics.length===4?'。選んだ所持遺物を失います。':''),{type:'REWARD',id,target:value('rewardTarget'),treatment:value('treatment'),replace:value('replace')});break;
 case 'descend':dispatch({type:'DESCEND'});break;
 case 'ascend':confirm('浮上を開始','このランでは下降へ戻れません。2つの代償イベントを通過して帰還します。',{type:'ASCEND'});break;
 case 'safe':dispatch({type:'SAFE',id,target:value('safeTarget')});break;
 case 'event':{const opt=eventOptions(state).find(o=>o.id===Number(b.dataset.choice));confirm(opt.name,opt.text,{type:'EVENT',choice:opt.id});break;}
 case 'core':confirm('記録核の処置を確定','この選択で浮上の代償と結末が変わります。変更できません。',{type:'CORE',id});break;
 case 'ascentChoice':confirm('浮上の代償',ascentOptions(state).find(o=>o.id===id).text,{type:'ASCENT_CHOICE',id,target:id==='discard'?value('ascentRelic'):value('ascentCrew')});break;
 case 'dismissIntro':dispatch({type:'DISMISS_INTRO'});break;
 case 'confirm':{const a=pending;pending=null;dialog.close();if(typeof a==='function')a();else if(a)dispatch(a);break;}
 case 'close':pending=null;dialog.close();render();break;
}});
dialog.addEventListener('cancel',()=>{pending=null;render();});
window.addEventListener('error',e=>{$('#announcer').textContent='エラーが発生しました';showDialog('ゲームの表示で問題が発生しました',`<p>${escape(e.message)}</p><p>直前の保存から再開できます。</p>${btn('タイトルへ戻る','title')}`);});
render();

installKeyboardNavigation(app,dialog);
