'use strict';
(() => {
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d'), W=480,H=720;
const MAX_HP=100,MAX_WEAPONS=3;
const supports=[{name:'船体修復',desc:'HPを25回復する。',icon:'＋'},{name:'緊急バリア',desc:'4秒間、敵の攻撃を無効化する。',icon:'◇'},{name:'弾幕消去',desc:'画面内の敵弾を消去。スコア +1,500。',icon:'✳'}];
const weapons=[
{name:'パルスキャノン',en:'PULSE CANNON',icon:'⋮',color:'#76f5c5',evo:'ノヴァ・テンペスト',desc:'連射速度と弾数が増加。',evoDesc:'5連装の貫通弾幕で、艦隊を一掃する。'},
{name:'拡散ショット',en:'SCATTER SHOT',icon:'⋔',color:'#ffc47c',evo:'ソーラー・ブロッサム',desc:'扇状に広がる弾丸を発射。',evoDesc:'13方向の灼熱弾。敵を貫き、空を染める。'},
{name:'プラズマレーザー',en:'PLASMA LASER',icon:'ϟ',color:'#8ecfff',evo:'ヘブンズ・ピラー',desc:'敵を貫通する高出力ビーム。',evoDesc:'3本の極太レーザーで戦場を焼き払う。'},
{name:'追尾ミサイル',en:'HOMING MISSILE',icon:'⌁',color:'#ff94bd',evo:'セラフィム・スウォーム',desc:'敵を追いかける爆発ミサイル。',evoDesc:'8発の追尾弾が連続爆発を巻き起こす。'},
{name:'チェインライトニング',en:'CHAIN LIGHTNING',icon:'↯',color:'#c4a2ff',evo:'ゼウス・ジャッジメント',desc:'近くの敵へ連鎖する雷撃。',evoDesc:'全域に届く連鎖雷撃。逃げ場はない。'},
{name:'オービタル',en:'ORBITAL DRONE',icon:'◈',color:'#f1e890',evo:'エクリプス・リング',desc:'随伴する衛星が自動援護射撃。',evoDesc:'6機の衛星が回転弾幕と防弾フィールドを展開。'}];
let state='title',ship={x:240,y:630,hp:MAX_HP,inv:0},wave=1,score=0,xp=0,level=1,need=6,time=0,waveTime=0,spawnClock=0,spawned=0,levels=[1,0,0,0,0,0],cd=[0,0,0,0,0,0],enemies=[],bullets=[],hostile=[],particles=[],gems=[],effects=[],keys={},shieldCd=0,sound=false,audio=null,best=0,shake=0,flash=0,kills=0,choices=[],pointer=null,transition=0,toastTimer=0,visualTime=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{best=Number(localStorage.getItem('void-bloom-best'))||0;}catch{}
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const stars=Array.from({length:100},()=>({x:rand(0,W),y:rand(0,H),z:rand(.2,1),s:rand(.5,1.6)}));
function tone(freq=440,dur=.1,type='sine',vol=.04,slide=0){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}
function unlockAudio(){if(!audio){const Audio=window.AudioContext||window.webkitAudioContext;if(Audio)audio=new Audio();}audio?.resume().catch(()=>{});}
function toast(text,color='#76f5c5'){const el=$('toast');el.textContent=text;el.style.color=color;el.classList.add('show');toastTimer=2.4;}
function burst(x,y,c,count=16,force=1){for(let i=0;i<count;i++){const a=rand(0,Math.PI*2),v=rand(25,160)*force;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.2,.8),max:.8,c,s:rand(1,4)});}if(particles.length>650)particles.splice(0,particles.length-650);}
function ring(x,y,c,r=70){effects.push({type:'ring',x,y,c,r,life:.45,max:.45});}
function ui(){ $('wave').innerHTML=String(wave).padStart(2,'0')+' <em>/ 12</em>';$('score').textContent=String(score).padStart(6,'0');$('health').textContent=Math.ceil(ship.hp)+' / '+MAX_HP;$('hpFill').style.width=(ship.hp/MAX_HP*100)+'%';$('hpFill').classList.toggle('low',ship.hp<=30);$('focus').classList.toggle('active',!!keys.Space);$('focus').setAttribute('aria-pressed',!!keys.Space);$('level').textContent='LV. '+String(level).padStart(2,'0');$('xp').style.width=Math.min(100,xp/need*100)+'%';$('xpText').textContent=Math.floor(xp)+' / '+need+' XP';$('best').textContent=String(best).padStart(6,'0');}
function arsenal(){ $('weaponCount').textContent=String(levels.filter(Boolean).length).padStart(2,'0')+' / 03';$('arsenal').innerHTML=weapons.map((w,i)=>`<div class="weapon ${levels[i]?'':'locked'}" style="--c:${w.color}"><span class="weapon-icon">${w.icon}</span><div class="weapon-info"><b>${levels[i]===5?w.evo:w.name}</b><small>${levels[i]===5?'EVOLUTION':!levels[i]&&levels.filter(Boolean).length>=MAX_WEAPONS?'装備枠がいっぱい':w.en}</small><div class="pips">${[1,2,3,4,5].map(n=>`<i class="${levels[i]>=n?'on':''}"></i>`).join('')}</div></div><span class="weapon-level">${levels[i]===5?'✦':levels[i]?'L'+levels[i]:'—'}</span></div>`).join('');}
function title(){state='title';$('overlay').className='overlay';$('overlay').innerHTML='<span class="badge">INVADER × ROGUELIKE</span><h2>VOID<br><span>BLOOM</span></h2><p>最後の一機。無限の進化。<br>あなただけの武装で、虚空を切り開け。</p><div class="ship-emblem">⟐</div><p>移動は WASD / 矢印キー / ドラッグ<br>常時オート射撃。Space長押しで低速移動。</p><button class="start" id="start">出撃する　↗</button><span class="subtext">12 WAVES · 6 WEAPONS · 3 SLOTS</span>';$('start').onclick=start;}
function start(){unlockAudio();state='playing';ship={x:240,y:630,hp:MAX_HP,inv:2};wave=1;score=0;xp=0;level=1;need=6;time=0;waveTime=0;spawnClock=0;spawned=0;levels=[1,0,0,0,0,0];cd=[0,0,0,0,0,0];enemies=[];bullets=[];hostile=[];gems=[];effects=[];particles=[];kills=0;transition=0;keys={};pointer=null;shieldCd=0;shake=0;flash=0;$('overlay').innerHTML='';$('overlay').className='overlay';$('pause').textContent='Ⅱ';$('bossHud').hidden=true;ui();arsenal();toast('WAVE 01 — FIRST CONTACT');}
function pause(){if(state==='playing'){state='paused';keys={};pointer=null;$('pause').textContent='▶';$('overlay').className='overlay';$('overlay').innerHTML='<span class="badge">FLIGHT SUSPENDED</span><h2>PAUSED</h2><p>ひと息ついたら、また宇宙へ。</p><button class="start" id="resume">戦闘に戻る</button>';$('resume').onclick=pause;}else if(state==='paused'){state='playing';$('overlay').innerHTML='';$('pause').textContent='Ⅱ';}}
function finish(win){state=win?'won':'lost';pointer=null;keys={};best=Math.max(best,score);try{localStorage.setItem('void-bloom-best',best);}catch{}ui();$('overlay').className='overlay';$('overlay').innerHTML=`<span class="badge">${win?'MISSION COMPLETE':'SIGNAL LOST'}</span><h2>${win?'VOID<br><span>CLEARED</span>':'ONE MORE<br><span>FLIGHT</span>'}</h2><p>${win?'虚空のコアを撃破。宇宙に光が戻った。':'進化の可能性は、まだ尽きない。'}</p><div class="result-stats"><div><b>${score.toLocaleString()}</b><small>SCORE</small></div><div><b>${wave}</b><small>WAVE</small></div><div><b>${kills}</b><small>KILLS</small></div></div><button class="start" id="retry">もう一度、出撃する　↗</button>`;$('retry').onclick=start;tone(win?660:180,.7,'triangle',.1,win?400:-120);}
function levelUp(){if(state!=='playing'||xp<need)return;xp-=need;level++;need=Math.round(10+level*3);state='upgrade';keys={};pointer=null;const available=levels.map((l,i)=>({i,l})).filter(w=>w.l<5&&(w.l>0||levels.filter(Boolean).length<MAX_WEAPONS));choices=[];const owned=available.filter(w=>w.l>0);if(owned.length)choices.push(owned.sort((a,b)=>b.l-a.l)[0].i);const pool=available.filter(w=>!choices.includes(w.i));while(choices.length<3&&pool.length){choices.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0].i);}let support=0;while(choices.length<3)choices.push(-1-support++);$('overlay').className='overlay upgrades';$('overlay').innerHTML=`<span class="badge">LEVEL ${String(level).padStart(2,'0')} REACHED</span><h2>CHOOSE YOUR POWER</h2><p>次の一撃を、選ぼう。 <span>1 / 2 / 3 キーでも選択</span></p>`+choices.map((i,n)=>{if(i<0){const support=supports[-i-1];return `<button class="choice" data-choice="${n}" style="--c:#76f5c5"><span class="weapon-icon">${support.icon}</span><div><span class="tag">${n+1} / SUPPORT</span><b>${support.name}</b><small>${support.desc}</small></div></button>`};const w=weapons[i],evo=levels[i]===4;return `<button class="choice ${evo?'evolved':''}" data-choice="${n}" style="--c:${w.color}"><span class="weapon-icon">${w.icon}</span><div><span class="tag">${n+1} / ${evo?'✦ EVOLUTION':levels[i]?'UPGRADE · LV.'+(levels[i]+1):'NEW WEAPON'}</span><b>${evo?w.evo:w.name}</b><small>${evo?w.evoDesc:w.desc}</small></div></button>`;}).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));tone(880,.25,'sine',.08,400);ui();}
function choose(n){if(state!=='upgrade'||!Number.isInteger(n)||n<0||n>=choices.length)return;const i=choices[n];if(i<0){if(i===-1)ship.hp=Math.min(MAX_HP,ship.hp+25);if(i===-2)ship.inv=Math.max(ship.inv,4);if(i===-3){score+=1500;hostile=[];}}else{if(!levels[i]&&levels.filter(Boolean).length>=MAX_WEAPONS)return;levels[i]++;cd[i]=0;if(levels[i]===5){flash=.7;shake=reduced?0:12;ring(ship.x,ship.y,weapons[i].color,550);burst(ship.x,ship.y,weapons[i].color,80,2);hostile=[];toast('EVOLUTION — '+weapons[i].evo,weapons[i].color);tone(330,.7,'sawtooth',.06,1000);}}state='playing';ship.inv=Math.max(ship.inv,1.5);$('overlay').innerHTML='';$('overlay').className='overlay';arsenal();ui();levelUp();}
function enemy(x,y,type=0,boss=false){const hp=boss? (wave===12?6800:1500+wave*160):Math.round(4+wave*1.4+wave*wave*.18)+(type===2?5+wave:0);return {x,y,type,boss,hp,max:hp,r:boss?47:16,v:rand(15,24)+wave*2,t:rand(0,6.28),fire:rand(2.5,5),hit:0};}
function spawn(){if(wave%4===0){if(!spawned){enemies.push(enemy(240,-70,3,true));spawned=1;toast(wave===12?'FINAL WAVE — VOID CORE':'WARNING — DREADNOUGHT','#ff94bd');$('bossHud').hidden=false;}return;}const rows=3+Math.floor(wave/3);if(spawned>=rows)return;const count=5+Math.min(2,Math.floor(wave/4));for(let i=0;i<count;i++)enemies.push(enemy(65+i*(350/(count-1)),-35-spawned%2*14,Math.floor(rand(0,Math.min(3,1+wave/3)))));spawned++;}
function bullet(x,y,vx,vy,dmg,c,r=3,pierce=false,homing=false){bullets.push({x,y,vx,vy,dmg,c,r,pierce,homing,life:3.5,hit:new Set()});}
function target(x,y){let near=null,d=Infinity;for(const e of enemies){if(e.hp<=0||e.y<0)continue;const dd=(e.x-x)**2+(e.y-y)**2;if(dd<d){near=e;d=dd;}}return near;}
function damage(e,dmg,c){if(e.hp<=0)return;e.hp-=dmg;e.hit=.075;if(e.hp<=0){kills++;score+=e.boss?5000:100+wave*15;burst(e.x,e.y,c,e.boss?90:15,e.boss?2:1);ring(e.x,e.y,c,e.boss?220:30);shake=Math.max(shake,reduced?0:e.boss?14:2);tone(e.boss?80:rand(120,220),e.boss?.6:.09,'triangle',e.boss?.12:.025,-60);const count=e.boss?20:1;for(let j=0;j<count;j++)gems.push({x:e.x+rand(-15,15),y:e.y+rand(-15,15),v:e.boss?3:2});if(e.boss){hostile=[];$('bossHud').hidden=true;ship.hp=Math.min(MAX_HP,ship.hp+10);}}}
function shoot(dt){for(let i=0;i<6;i++)cd[i]-=dt;for(let i=0;i<6;i++){const l=levels[i];if(!l||cd[i]>0)continue;const w=weapons[i],ev=l===5,c=w.color;
if(i===0){cd[i]=ev?.12:.32-l*.035;const n=ev?5:l>=3?3:l>=2?2:1;for(let j=0;j<n;j++)bullet(ship.x+(j-(n-1)/2)*10,ship.y-20,(j-(n-1)/2)*(ev?40:13),-570,ev?5:1.5+l*.5,c,ev?4:3,ev);tone(530,.04,'square',.009,150);}
if(i===1){cd[i]=ev?.45:.95-l*.09;const n=ev?13:3+l;for(let j=0;j<n;j++){const a=-Math.PI/2+(j-(n-1)/2)*(ev?.11:.14);bullet(ship.x,ship.y-16,Math.cos(a)*440,Math.sin(a)*440,ev?5:2+l*.5,c,ev?4:3,ev);}}
if(i===2){cd[i]=ev?.75:1.9-l*.15;const xs=ev?[ship.x-70,ship.x,ship.x+70]:[ship.x];for(const x of xs){const width=ev?40:8+l*4;effects.push({type:'beam',x,y:ship.y-20,w:width,c,life:.3,max:.3});for(const e of enemies)if(Math.abs(e.x-x)<width/2+e.r&&e.y<ship.y)damage(e,ev?35:10+l*5,c);}tone(180,.2,'sawtooth',.025,600);}
if(i===3){cd[i]=ev?.65:1.6-l*.1;for(let n=0;n<(ev?8:l+1);n++)bullet(ship.x+(n-(l/2))*12,ship.y-10,rand(-180,180),-220,ev?19:6+l*2,c,5,false,true);}
if(i===4){cd[i]=ev?.75:2.2-l*.16;let from={x:ship.x,y:ship.y-20};const hit=new Set();for(let n=0;n<(ev?18:l+2);n++){const pool=enemies.filter(e=>e.hp>0&&e.y>0&&!hit.has(e)).sort((a,b)=>(a.x-from.x)**2+(a.y-from.y)**2-((b.x-from.x)**2+(b.y-from.y)**2));const e=pool[0];if(!e)break;hit.add(e);effects.push({type:'lightning',x:from.x,y:from.y,tx:e.x,ty:e.y,c,life:.22,max:.22});damage(e,ev?25:5+l*3,c);from=e;}}
if(i===5){cd[i]=ev?.17:.5-l*.04;for(let n=0;n<(ev?6:Math.min(4,l+1));n++){const a=time*1.7+n*Math.PI*2/(ev?6:Math.min(4,l+1));const x=ship.x+Math.cos(a)*44,y=ship.y+Math.sin(a)*25;bullet(x,y,Math.cos(a)*60,-500,ev?6:2+l,c,3,ev);}}}}
function hurt(amount=12+wave){if(ship.inv>0||state!=='playing')return;ship.hp=Math.max(0,ship.hp-amount);ship.inv=1.1;shake=reduced?0:12;flash=.2;burst(ship.x,ship.y,'#ff698e',25);tone(110,.3,'sawtooth',.06,-70);ui();if(ship.hp<=0)finish(false);}
function update(dt){visualTime+=dt;for(const s of stars){s.y+=(state==='playing'?28:9)*s.z*dt;if(s.y>H){s.y=0;s.x=rand(0,W);}}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('show');}if(state!=='playing')return;time+=dt;waveTime+=dt;ship.inv-=dt;shieldCd=Math.max(0,shieldCd-dt);const movementSpeed=keys.Space?150:300;shake=Math.max(0,shake-dt*30);flash=Math.max(0,flash-dt);let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),dy=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(dx||dy){const norm=Math.hypot(dx,dy);ship.x+=dx/norm*movementSpeed*dt;ship.y+=dy/norm*movementSpeed*dt;}if(pointer){const px=pointer.x-ship.x,py=pointer.y-ship.y,distance=Math.hypot(px,py),step=Math.min(distance,movementSpeed*dt);ship.x+=px/(distance||1)*step;ship.y+=py/(distance||1)*step;}ship.x=clamp(ship.x,22,W-22);ship.y=clamp(ship.y,H*.72,H-25);
spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=2.2;}shoot(dt);
for(const e of enemies){if(e.hp<=0)continue;e.t+=dt;e.hit-=dt;e.fire-=dt;if(e.boss){e.y=Math.min(135,e.y+dt*65);e.x=240+Math.sin(e.t*.65)*145;if(e.fire<=0&&e.y>90){const n=wave===12?17:11;for(let j=0;j<n;j++){const a=Math.PI/2+(j-(n-1)/2)*.16+Math.sin(e.t)*.2;hostile.push({x:e.x,y:e.y+30,vx:Math.cos(a)*(150+wave*4),vy:Math.sin(a)*(150+wave*4),r:6,dmg:18+wave});}e.fire=wave===12?.7:1;}$('bossLife').style.width=Math.max(0,e.hp/e.max*100)+'%';}else{e.y+=e.v*dt;e.x+=Math.cos(e.t*1.4)*dt*(e.type===1?24:9);if(e.fire<=0&&e.y>35&&e.y<510&&time>7){const aim=Math.atan2(ship.y-e.y,ship.x-e.x);const count=e.type===2&&wave>=3?3:1;for(let j=0;j<count;j++){const a=aim+(j-(count-1)/2)*.18;hostile.push({x:e.x,y:e.y+15,vx:Math.cos(a)*(105+wave*5),vy:Math.sin(a)*(105+wave*5),r:5,dmg:10+wave+e.type*2});}e.fire=rand(2.5,4.5)/(1+wave*.055);}if(e.y>H-10){e.hp=0;hurt(15+wave);}}if(Math.hypot(e.x-ship.x,e.y-ship.y)<e.r+13){hurt(22+wave);if(!e.boss)damage(e,999,'#ff698e');}}
for(const b of bullets){b.life-=dt;if(b.homing){const e=target(b.x,b.y);if(e){const angle=Math.atan2(e.y-b.y,e.x-b.x);b.vx+=(Math.cos(angle)*390-b.vx)*dt*5;b.vy+=(Math.sin(angle)*390-b.vy)*dt*5;}if(Math.random()<.5)particles.push({x:b.x,y:b.y,vx:0,vy:30,life:.2,max:.2,c:b.c,s:2});}b.x+=b.vx*dt;b.y+=b.vy*dt;for(const e of enemies){if(e.hp<=0||b.hit.has(e))continue;if(Math.abs(e.y-b.y)<e.r+b.r+8&&Math.abs(e.x-b.x)<e.r+b.r){b.hit.add(e);damage(e,b.dmg,b.c);if(b.homing){ring(b.x,b.y,b.c,55);for(const o of enemies)if(o!==e&&Math.hypot(o.x-b.x,o.y-b.y)<70)damage(o,b.dmg*.6,b.c);}if(!b.pierce){b.life=0;break;}}}}
bullets=bullets.filter(b=>b.life>0&&b.y>-40&&b.y<H+50&&b.x>-80&&b.x<W+80);for(const b of hostile){b.x+=b.vx*dt;b.y+=b.vy*dt;if(levels[5]===5&&shieldCd<=0&&Math.hypot(b.x-ship.x,b.y-ship.y)<42){b.y=H+100;shieldCd=.45;burst(b.x,ship.y,'#f1e890',4);}else if(Math.hypot(b.x-ship.x,b.y-ship.y)<b.r+8){b.y=H+100;hurt(b.dmg);}}hostile=hostile.filter(b=>b.y<H+20&&b.x>-30&&b.x<W+30);
for(const g of gems){const d=Math.hypot(ship.x-g.x,ship.y-g.y);const speed=190+Math.max(0,450-d);g.x+=(ship.x-g.x)/(d||1)*speed*dt;g.y+=(ship.y-g.y)/(d||1)*speed*dt;if(d<20){g.dead=true;xp+=g.v;score+=10;}}gems=gems.filter(g=>!g.dead);
for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98;}particles=particles.filter(p=>p.life>0);for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);enemies=enemies.filter(e=>e.hp>0);
const done=spawned>=(wave%4===0?1:3+Math.floor(wave/3));if(done&&!enemies.length&&!gems.length){transition+=dt;if(transition>1.5){if(wave===12){finish(true);return;}wave++;waveTime=0;spawned=0;spawnClock=.8;transition=0;hostile=[];ship.hp=Math.min(MAX_HP,ship.hp+5);toast('WAVE '+String(wave).padStart(2,'0')+' — '+(wave%4===0?'CORE APPROACH':'DEEPER INTO THE VOID'));}}else transition=0;$('timer').textContent=Math.floor(time/60).toString().padStart(2,'0')+':'+Math.floor(time%60).toString().padStart(2,'0');ui();levelUp();}
function glow(c,blur=10){ctx.fillStyle=c;ctx.strokeStyle=c;ctx.shadowColor=c;ctx.shadowBlur=reduced?0:blur;}
const sprites=[['001000100','000101000','001111100','011010110','111111111','101111101','101000101','000101000'],['000111000','001111100','011111110','110101011','111111111','001101100','011000110','110000011'],['001111100','011111110','110101011','111111111','000111000','001010100','010000010','100000001']];
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);const c=e.hit>0?'#ffffff':e.boss?'#ff719c':e.type===0?'#90e0c2':e.type===1?'#b2a1f5':'#ffbf82';glow(c,e.boss?22:8);if(e.boss){ctx.rotate(Math.sin(e.t)*.1);ctx.beginPath();for(let j=0;j<8;j++){const a=j*Math.PI/4,r=j%2?26:53;const x=Math.cos(a)*r,y=Math.sin(a)*r;j?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.stroke();ctx.fillStyle='#261326';ctx.fill();ctx.rotate(-e.t*.4);ctx.strokeRect(-23,-23,46,46);glow('#ffb7d0',25);ctx.beginPath();ctx.arc(0,0,13+Math.sin(e.t*5)*3,0,7);ctx.fill();}else{const map=sprites[e.type%3];map.forEach((row,y)=>[...row].forEach((bit,x)=>{if(bit==='1')ctx.fillRect((x-4.5)*3,(y-4)*3,2.8,2.8);}));}ctx.restore();}
function drawShip(x,y,demo=false){ctx.save();ctx.translate(x,y);if(!demo&&ship.inv>0&&Math.floor(time*12)%2)ctx.globalAlpha=.4;glow('#76f5c5',18);ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(16,17);ctx.lineTo(5,10);ctx.lineTo(0,15);ctx.lineTo(-5,10);ctx.lineTo(-16,17);ctx.closePath();ctx.fillStyle='#123e3a';ctx.fill();ctx.stroke();glow('#caffed',12);ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(4,5);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();glow('#74d9ff',15);ctx.beginPath();ctx.moveTo(-4,18);ctx.lineTo(0,28+Math.sin(visualTime*35)*7);ctx.lineTo(4,18);ctx.fill();ctx.restore();}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#070c17';ctx.fillRect(0,0,W,H);const bg=ctx.createRadialGradient(250,270,0,240,300,420);bg.addColorStop(0,'#112b3040');bg.addColorStop(1,'#080c1600');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.save();if(shake&&!reduced)ctx.translate(rand(-shake,shake),rand(-shake,shake));ctx.shadowBlur=0;for(const s of stars){ctx.globalAlpha=.25+s.z*.6;ctx.fillStyle=s.z>.8?'#a5d9d0':'#657d9f';ctx.fillRect(s.x,s.y,s.s,s.s);}ctx.globalAlpha=1;ctx.strokeStyle='#2e706221';ctx.lineWidth=1;ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(0,H*.7);ctx.lineTo(W,H*.7);ctx.stroke();ctx.setLineDash([]);const zone=ctx.createLinearGradient(0,H*.7,0,H);zone.addColorStop(0,'#55e6b501');zone.addColorStop(1,'#55e6b50b');ctx.fillStyle=zone;ctx.fillRect(0,H*.7,W,H*.3);
if(state==='title'){for(let row=0;row<3;row++)for(let n=0;n<7;n++)drawEnemy({x:57+n*61+Math.sin(visualTime)*6,y:92+row*54,type:row,hit:0,t:visualTime});drawShip(240,630,true);}else{for(const g of gems){ctx.save();ctx.translate(g.x,g.y);ctx.shadowBlur=0;ctx.fillStyle='#0d343c';ctx.strokeStyle='#72ebef';ctx.lineWidth=1.5;ctx.fillRect(-10,-7,20,14);ctx.strokeRect(-10,-7,20,14);ctx.fillStyle='#a2fcff';ctx.font='bold 9px monospace';ctx.textAlign='center';ctx.fillText('XP',0,3);ctx.restore();}for(const e of enemies)drawEnemy(e);for(const b of bullets){glow(b.c,10);ctx.lineWidth=b.r*1.4;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.018,b.y-b.vy*.018);ctx.stroke();ctx.fillStyle='#fff';ctx.fillRect(b.x-1,b.y-3,2,4);}drawShip(ship.x,ship.y);if(levels[5]){const n=levels[5]===5?6:Math.min(4,levels[5]+1);for(let j=0;j<n;j++){const a=time*1.7+j*Math.PI*2/n,x=ship.x+Math.cos(a)*44,y=ship.y+Math.sin(a)*25;glow('#f1e890',12);ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.strokeRect(-5,-5,10,10);ctx.restore();}if(levels[5]===5){ctx.globalAlpha=.25;ctx.beginPath();ctx.ellipse(ship.x,ship.y,48,32,0,0,7);ctx.stroke();ctx.globalAlpha=1;}}}
for(const e of effects){ctx.globalAlpha=Math.max(0,e.life/e.max);glow(e.c,20);if(e.type==='ring'){ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r*(1-e.life/e.max),0,7);ctx.stroke();}else if(e.type==='beam'){ctx.fillStyle=e.c;ctx.fillRect(e.x-e.w/2,0,e.w,e.y);ctx.fillStyle='#eaffff';ctx.fillRect(e.x-e.w*.15,0,e.w*.3,e.y);}else{ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.x,e.y);for(let j=1;j<=8;j++)ctx.lineTo(e.x+(e.tx-e.x)*j/8+(j===8?0:rand(-14,14)),e.y+(e.ty-e.y)*j/8);ctx.stroke();}}ctx.globalAlpha=1;for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);glow(p.c,5);ctx.fillRect(p.x,p.y,p.s,p.s);}ctx.globalAlpha=1;ctx.shadowBlur=0;for(const b of hostile){ctx.save();const len=Math.hypot(b.vx,b.vy)||1;ctx.strokeStyle='#ff734d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x-b.vx/len*9,b.y-b.vy/len*9);ctx.lineTo(b.x-b.vx/len*19,b.y-b.vy/len*19);ctx.stroke();ctx.fillStyle='#36100c';ctx.beginPath();ctx.arc(b.x,b.y,b.r+2,0,7);ctx.fill();ctx.strokeStyle='#ff774f';ctx.lineWidth=2.5;ctx.stroke();ctx.fillStyle='#fff0b3';ctx.beginPath();ctx.arc(b.x,b.y,2.5,0,7);ctx.fill();ctx.restore();}if(keys.Space&&state==='playing'){ctx.strokeStyle='#ffffff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(ship.x,ship.y,8,0,7);ctx.stroke();ctx.fillStyle='#ffffff';ctx.fillRect(ship.x-2,ship.y-2,4,4);}ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.restore();if(flash&&!reduced){ctx.fillStyle=`rgba(180,255,226,${flash*.25})`;ctx.fillRect(0,0,W,H);}}
$('pause').onclick=pause;$('sound').onclick=()=>{unlockAudio();sound=!sound;$('sound').textContent='SOUND '+(sound?'ON':'OFF');if(sound)tone(660,.15);};
window.addEventListener('keydown',e=>{if((e.code==='Space'&&state==='playing')||(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&!['BUTTON','INPUT'].includes(document.activeElement.tagName)))e.preventDefault();if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){pause();return;}if(state==='upgrade'&&/^Digit[123]$/.test(e.code)){choose(Number(e.code.slice(-1))-1);return;}keys[e.code]=true;});window.addEventListener('keyup',e=>{keys[e.code]=false;});window.addEventListener('blur',()=>{keys={};pointer=null;if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});
function point(e){const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)*W/r.width,y:clamp((e.clientY-r.top)*H/r.height-25,H*.72,H-25)};}canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;canvas.setPointerCapture(e.pointerId);point(e);});canvas.addEventListener('pointermove',e=>{if(pointer&&state==='playing')point(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>{pointer=null;});$('focus').addEventListener('pointerdown',e=>{e.preventDefault();keys.Space=true;$('focus').setPointerCapture(e.pointerId);});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('focus').addEventListener(name,()=>{keys.Space=false;});
let previous=performance.now();function frame(now){const dt=Math.min(.033,(now-previous)/1000);previous=now;update(dt);draw();requestAnimationFrame(frame);}ui();arsenal();title();requestAnimationFrame(frame);
// Read-only diagnostics share the live game state; no gameplay cheats are exposed.
window.voidBloom={snapshot:()=>({state,wave,score,level,xp,need,kills,hp:ship.hp,time,weapons:[...levels],enemies:enemies.length,bullets:bullets.length,hostile:hostile.length,ship:{x:ship.x,y:ship.y},auto:true,focus:!!keys.Space,maxHp:MAX_HP})};
})();
