import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,reduce} from '../src/engine.js';
import {createField,performField} from '../src/field.js';
import {validateRun} from '../src/save.js';
const act=(s,id)=>reduce(s,{type:'FIELD_ACTION',id});
function begin(){let s=newRun('field','silent','A07');assert.deepEqual(s.routes.map(r=>r.anomaly),['A07']);s=reduce(s,{type:'SELECT_ROUTE',id:s.routes[0].id});return reduce(s,{type:'DISMISS_INTRO'});}
function isolate(){let s=begin();for(const id of ['listen-lock','move-lock','hold','signal','measure','move-bunk','normal','close'])s=act(s,id);return s;}
test('測定は状態を変えず、合図による介入だけが残留位置を変える',()=>{let s=begin(),oxygen=s.oxygen;for(const id of ['listen-lock','play','measure'])s=act(s,id);assert.match(s.field.last.text,/再生を止めた/);const baseline=s.field.last;for(const id of ['stop','move-lock','hold','measure'])s=act(s,id);assert.equal(s.field.values.trace,'none');s=act(s,'signal');assert.equal(s.field.values.trace,'lock');const world=structuredClone(s.field.values);s=act(s,'measure');assert.deepEqual(s.field.values,world);assert.equal(s.oxygen,oxygen-1);assert.equal(baseline.conditions['協力者'],'寝台');s=act(s,'move-bunk');s=act(s,'normal');s=act(s,'measure');assert.match(s.field.last.text,/無人/);assert.equal(s.deduction,null);assert.equal(reduce(s,{type:'TO_HYPOTHESIS'}),s);});
test('排気しても調査は終わらず再測定でき、撤収時に結末が決まる',()=>{let failed=act(act(begin(),'close'),'vent');assert.equal(failed.mysteryOutcome,null);let s=act(isolate(),'vent');assert.equal(s.phase,'investigation');assert.equal(s.field.stage,'aftercare');assert.equal(s.oxygen,6);assert.equal(s.field.values.trace,'gone');assert.equal(act(s,'open'),s);assert.equal(act(s,'vent'),s);s=act(s,'measure');assert.match(s.field.last.text,/真空/);s=act(s,'leave');assert.equal(s.mysteryOutcome.id,'severed');assert.equal(act(s,'open'),s);s=reduce(s,{type:'CONTINUE'});assert.equal(s.phase,'result');assert.equal(s.ending,'return');});
test('空回収からも観測・別の対処を続けられる',()=>{let s=begin();for(const id of ['hold','signal','close','recover'])s=act(s,id);assert.equal(s.field.values.container,'empty');assert.equal(s.field.values.trace,'bunk');assert.equal(s.phase,'investigation');s=act(s,'watch-container');assert.match(s.field.last.text,/乾いた/);s=act(s,'listen-bunk');s=act(s,'measure');assert.match(s.field.last.text,/寝台の下/);assert.equal(act(s,'recover'),s);assert.equal(act(s,'leave').mysteryOutcome.id,'leak');});
test('接触の条件を変え、名を記録してから標本回収または解放を選ぶ',()=>{let s=isolate();s=act(s,'call');assert.equal(s.field.values.contact,'heard');s=act(s,'cool');s=act(s,'long');s=act(s,'call');assert.equal(s.field.values.contact,'named');s=act(s,'supply');s=act(s,'recover');assert.equal(s.field.values.trace,'container');assert.equal(s.phase,'investigation');s=act(s,'watch-container');assert.match(s.field.last.text,/十秒ごと/);assert.equal(act(s,'leave').mysteryOutcome.id,'named-specimen');s=act(s,'release');assert.equal(s.field.values.trace,'gone');assert.equal(act(s,'release'),s);assert.equal(act(s,'leave').mysteryOutcome.id,'farewell');});
test('人命と区画の喪失は介入時に確定し、後から戻せない',()=>{let s=begin();for(const id of ['move-lock','close','vent'])s=act(s,id);assert.equal(s.crew.find(c=>c.id==='aoi').hp,0);assert.equal(act(s,'signal'),s);assert.equal(act(s,'move-bunk'),s);assert.equal(act(s,'leave').mysteryOutcome.id,'sacrifice');});
test('作戦・記録・対処後の状態が保存され、不正な根拠は拒否する',()=>{let s=isolate();const id=s.field.records.find(r=>r.measurement).id;s=reduce(s,{type:'FIELD_PLAN',goal:'船室から分離する',evidence:[id]});const restored=validateRun(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored.field,s.field);assert.equal(act(act(restored,'recover'),'leave').mysteryOutcome.id,'specimen');assert.equal(reduce(s,{type:'FIELD_PLAN',goal:'船室から分離する',evidence:[999]}),s);restored.field.values.person='unknown';assert.throws(()=>validateRun(restored));});
test('旧保存の現場と記録を保ち新しい状態項目を補完する',()=>{let s=begin();s.field.version=1;delete s.field.stage;delete s.field.plan;delete s.field.values.chamber;const restored=validateRun(s);assert.equal(restored.field.version,2);assert.equal(restored.field.values.chamber,'usable');assert.equal(restored.field.stage,'survey');});
test('共通エンジンは別の対象と法則のシナリオも扱う',()=>{const d={initial:{light:false},conditions:[{key:'light',label:'照明',options:{false:'消灯',true:'点灯'}}],actions:[{id:'switch',intervention:true,set:{light:true},text:'点灯'},{id:'look',measure:true,rules:[{when:{light:true},text:'影が二つ'},{text:'何も見えない'}]}]};let f=createField(d);assert.equal(performField(f,d,'look').field.last.text,'何も見えない');f=performField(f,d,'switch').field;assert.equal(f.stage,'aftercare');assert.equal(performField(f,d,'look').field.last.text,'影が二つ');assert.equal(performField(f,d,'unknown'),null);});
