import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,reduce,anomaly,commandPreview,intent,disease,visibleClues,effectivePower,eventOptions} from '../src/engine.js';
import {emptyMeta,updateMeta,validateRun} from '../src/save.js';
const act=(s,type,args={})=>reduce(s,{type,...args});
function setup(id='A01',hypothesis=null){let s=newRun('mechanics');s.node={id:'test',anomaly:id,event:null};s.phase='preparation';s.hypothesis=hypothesis;s.clues=[0,1];return s;}
test('誤仮説は汚染+1と即時の異常行動、未知仮説は罰なし',()=>{let s=act(setup('A01',0),'READY');assert.equal(s.contamination,1);assert.equal(s.crew[0].hp,2);s=act(setup(),'READY');assert.equal(s.contamination,0);assert.equal(s.crew[0].hp,3);});
test('手掛かりの0/1/2/3段階と予見・忘却',()=>{let s=act(setup(),'READY');s.clues=[];assert.match(intent(s).text,/不明/);s.clues=[0];assert.match(intent(s).text,/対象・規模は不明/);s.clues=[0,1];assert.match(intent(s).text,/体力−1/);s.clues=[0,1,2];s.modules[1].relic='box';assert.deepEqual(visibleClues(s),[1,2]);s.clues=[];s.modules[0].relic='rust';assert.match(intent(s).text,/体力−1/);});
test('各深度の研究・音響補正と3ターン目の配置交換',()=>{let s=setup();const base=commandPreview(s,'observe').value;s.depth=2;assert.equal(commandPreview(s,'observe').value,base+1);assert.equal(commandPreview(s,'silent').value,3);s.depth=3;s=act(s,'READY');for(let i=0;i<3;i++)s=act(s,'COMMAND',{id:'defend'});assert.equal(s.modules[0].crew,'aoi');assert.equal(s.modules[1].crew,'mio');});
test('配置不足と電力不足の命令は実行不可、行動不能は配置不可',()=>{let s=act(setup(),'READY');assert.throws(()=>act(s,'COMMAND',{id:'shock'}),/隊員/);assert.throws(()=>act(s,'COMMAND',{id:'seal'}),/電力/);s.phase='preparation';s.crew[0].fatigue=4;assert.throws(()=>act(s,'ASSIGN',{module:4,crew:'mio'}),/行動不能/);});
test('追加調査の2種類の代償と同じ地点の二重実行を防止',()=>{for(const payment of ['oxygen','fatigue']){let s=newRun('extra');s.routes[0].anomaly='A01';s=act(s,'SELECT_ROUTE',{id:s.routes[0].id});for(let i=0;i<2;i++)s=act(s,'INVESTIGATE',{site:i,crew:'mio',tool:true});const oxygen=s.oxygen;s=act(s,'INVESTIGATE',{site:2,crew:'ren',payment});assert.equal(s.clues.length,3);assert.equal(s.oxygen,oxygen-(payment==='oxygen'?1:0));assert.equal(s.crew[2].fatigue,payment==='fatigue'?1:0);assert.equal(act(s,'INVESTIGATE',{site:2,crew:'ren',payment}),s);}});
test('全設備観測で窓を抑制、白庭は傷を複製',()=>{let s=act(setup('A04'),'READY');const hp=s.hull;s=act(s,'COMMAND',{id:'defend'});assert.equal(s.encounter.blocked,null);assert.equal(s.hull,hp);s=setup('A02');s.modules[3].crew='ren';s.modules[2].crew=null;s.modules[3].power=2;s.modules[5].power=0;s.modules[4].power=0;s=act(s,'READY');s=act(s,'COMMAND',{id:'shock'});assert.equal(s.encounter.targets.observe,7);});
test('ミナモは再使用直前に損害、再配置で未来を変更',()=>{let s=setup('F01');s.modules[5].power=0;s=act(s,'READY');s=act(s,'COMMAND',{id:'defend'});const hp=s.hull;s=act(s,'COMMAND',{id:'defend'});assert.equal(s.hull,hp-2);s=act(s,'REPOSITION',{crew:'mio',module:4});assert.deepEqual(s.encounter.used,[]);assert.throws(()=>act(s,'REPOSITION',{crew:'mio',module:0}));});
test('時計は1回だけ巻き戻せ、酸素を消費し、リロード後も復元',()=>{let s=setup();s.relics=['clock'];s.modules[1].relic='clock';s=act(s,'READY');s=act(s,'COMMAND',{id:'defend'});const oxygen=s.oxygen;s=act(JSON.parse(JSON.stringify(s)),'REWIND');assert.equal(s.oxygen,oxygen-1);assert.equal(s.encounter.turn,1);s=act(s,'COMMAND',{id:'defend'});assert.equal(s.undo,null);assert.throws(()=>act(s,'REWIND'));});
test('遺物は4個まで、5個目は選択して交換',()=>{let s=setup();s.phase='reward';s.relics=['bell','coral','lens','specimen'];s.rewards=[{id:'relic:clock',kind:'relic',name:'昨日の時計',relic:'clock'}];assert.throws(()=>act(s,'REWARD',{id:'relic:clock'}),/交換/);s=act(s,'REWARD',{id:'relic:clock',replace:'bell'});assert.equal(s.relics.length,4);assert.ok(s.relics.includes('clock'));assert.ok(!s.relics.includes('bell'));});
test('音響・生体遺物の副作用と医務室による悪化防止',()=>{let s=setup();s.relics=['coral'];s=act(s,'EQUIP',{module:1,id:'coral'});assert.equal(s.crew[2].fatigue,1);assert.equal(s.crew[1].diseases[0].id,'echo');s.modules[0].power=0;s.modules[4].power=2;s=act(s,'READY');assert.equal(s.crew[1].fatigue,0);assert.equal(s.encounter.medUsed,true);disease(s,s.crew[1],'dark');assert.equal(s.crew[1].diseases.length,2);});
test('古いrevisionの確定を再適用せず連打を防ぐ',()=>{let s=act(setup(),'READY');const a={type:'COMMAND',id:'defend',revision:s.revision};s=reduce(s,a);assert.equal(reduce(s,a),s);});
test('未知の保存IDと構造を拒否する',()=>{let s=newRun('invalid');s.routes[0].anomaly='bad';assert.throws(()=>validateRun(s));s=newRun('invalid');s.modules[0].power=3;assert.throws(()=>validateRun(s));});
test('同じシードの独立ランは別々に帰還数へ加算',()=>{let s=setup();s.ending='return';s.sessionId='first';let m=updateMeta(emptyMeta(),s);s.sessionId='second';m=updateMeta(m,s);assert.equal(m.returns,2);});
