import test from 'node:test';import assert from 'node:assert/strict';
import {newRun,reduce} from '../src/engine.js';
import {MYSTERIES} from '../src/data.js';
const act=(s,type,args={})=>reduce(s,{type,...args});
function investigated(id='A07'){let s=newRun('vertical');s.routes[0].anomaly=id;s=act(s,'SELECT_ROUTE',{id:s.routes[0].id});s=act(s,'INVESTIGATE',{site:0,crew:'mio',tool:true});s=act(s,'INVESTIGATE',{site:1,crew:'aoi',tool:true});return act(s,'TO_HYPOTHESIS');}
test('航海ログにも答えではなく観測事実だけを残す',()=>{const s=investigated();const entries=s.history.filter(h=>h.category==='investigation').map(h=>h.summary).join('\n');assert.match(entries,/02:14:07/);assert.doesNotMatch(entries,/意図して黙った時だけ/);});
test('調査から3軸推理、予測つき実証、危機へ進む',()=>{let s=investigated(),m=MYSTERIES.A07;s=act(s,'DEDUCE',{trigger:1,nature:1,response:1});assert.equal(s.phase,'verification');assert.equal(s.insight,3);s=act(s,'EXPERIMENT',{id:'hold',target:'mio',prediction:1});assert.equal(s.experimentResults[0].predictionCorrect,true);s=act(s,'TO_CRISIS');assert.equal(s.phase,'crisis');assert.equal(s.insight,3);assert.ok(m.outcomes.some(o=>o.id==='accept'));});
test('予測を外しても新証拠を得て推理を修正できる',()=>{let s=investigated();s=act(s,'DEDUCE',{trigger:0,nature:0,response:0});s=act(s,'EXPERIMENT',{id:'recording',target:'aoi',prediction:0});assert.equal(s.experimentResults[0].predictionCorrect,false);assert.ok(s.experimentResults[0].reaction);s=act(s,'REVISE');assert.equal(s.phase,'deduction');s=act(s,'DEDUCE',{trigger:1,nature:1,response:1});assert.equal(s.experimentResults.length,1);assert.equal(s.insight,3);});
test('発見していない決断は選べず、撤退結末は記録される',()=>{let s=investigated();s=act(s,'DEDUCE',{trigger:0,nature:0,response:0});s=act(s,'EXPERIMENT',{id:'hold',target:'mio',prediction:0});s=act(s,'TO_CRISIS');assert.throws(()=>act(s,'OUTCOME',{id:'accept'}),/観測または実証/);s=act(s,'OUTCOME',{id:'escape'});assert.equal(s.phase,'aftermath');assert.equal(s.records.at(-1).ending,'酸素区画を切り離す');assert.equal(s.mysteryOutcome.reveal,false);});
test('四人目の呼吸を二度予測し、名前を得ると受容結末へ到達できる',()=>{let s=investigated();s=act(s,'DEDUCE',{trigger:1,nature:1,response:1});s=act(s,'EXPERIMENT',{id:'hold',target:'mio',prediction:1});s=act(s,'EXPERIMENT',{id:'call',target:'aoi',prediction:1});s=act(s,'TO_CRISIS');s=act(s,'OUTCOME',{id:'accept'});assert.match(s.mysteryOutcome.truth,/冬城ユラ/);assert.match(s.mysteryOutcome.text,/四人/);s=act(s,'CONTINUE');assert.equal(s.phase,'decision');});
